In [1]:
%pip install optuna

Collecting optuna
  Downloading optuna-4.6.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.1)
Collecting colorlog (from optuna)
  Downloading colorlog-6.10.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)
Downloading optuna-4.6.0-py3-none-any.whl (404 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 404.7/404.7 kB 11.3 MB/s eta 0:00:00
Downloading colorlog-6.10.1-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, optuna
Successfully installed colorlog-6.10.1 optuna-4.6.0

In [2]:
import warnings
from functools import partial

import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.feature_selection import RFECV
from sklearn.experimental import enable_halving_search_cv
from sklearn.compose import TransformedTargetRegressor
from sklearn.preprocessing import MinMaxScaler, FunctionTransformer
from sklearn.base import TransformerMixin, RegressorMixin, BaseEstimator
from sklearn.model_selection import TimeSeriesSplit, HalvingRandomSearchCV, train_test_split, GridSearchCV, ParameterGrid
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error, make_scorer
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor, early_stopping, lgb

import inspect
import optuna

import requests
from functools import reduce

from scipy.stats import loguniform, randint, uniform

from google.colab import drive
drive.mount('/content/drive')

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

Mounted at /content/drive

In [3]:
def MirrorLog(X, c:float=(1/3)):

    '''
    X   :   The data that will be mirror-log transformed.
    c   :   Constant parameter. Default is 1/3, as suggested in the literature.
    '''

    X = np.asarray(X)
    X_new = np.empty_like(X)
    X_new[X != 0] = np.sign(X[X != 0]) * (np.log(np.abs(X[X != 0]) * (1/c)) + np.log(c))
    X_new[X == 0] = 0
    return X_new

# reverses the mirror log transformation, restoring data—including negative or zero values—back to its original scale by undoing the signed logarithmic mapping.
def InverseMirrorLog(X, c:float=(1/3)):

    '''
    X   :   The data that will be inverse mirror-log transformed.
    c   :   Constant parameter. Default is 1/3, as suggested in the literature.
    '''

    X = np.asarray(X)
    X_inv = np.empty_like(X)
    X_inv[X != 0] = np.sign(X[X != 0]) * (np.exp(np.abs(X[X != 0]) - np.log(c)) - (1/c))
    X_inv[X == 0] = 0
    return X_inv


class MirrorLogNormScaler(TransformerMixin, BaseEstimator):

    def __init__(self, mirrorlog_kwargs:dict=None, normalizer=None):

        '''
        mirrorlog_kwargs    :   Keyword arguments for the mirror-log transformation. Default is {'c': 1/3}.
        normalizer          :   Normalizer to use after mirror-log transformation. Default is MinMaxScaler.
        '''

        self.mirrorlog_kwargs = mirrorlog_kwargs
        self.normalizer = normalizer
        _normalizer = self.normalizer or MinMaxScaler()
        self._normalizer = _normalizer

        mirrorlog_kwargs_ = self.mirrorlog_kwargs or {'c': 1/3}

        self._mlog_scaler = FunctionTransformer(
            func=partial(MirrorLog, **mirrorlog_kwargs_),
            inverse_func=partial(InverseMirrorLog, **mirrorlog_kwargs_),
            check_inverse=False
        )

    def fit(self, X, y=None):

        '''
            X   :   The data that will be mirror-log transformed then used to compute the per-feature minimum and maximum used for later scaling along the features axis.
            y   :   Ignored.
        '''

        X_mlog = self._mlog_scaler.fit_transform(X)
        self._normalizer.fit(X_mlog)
        return self

    def transform(self, X):

        '''
        X   :   The data that will be mirror-log transformed then min-max scaled.
        '''

        X_mlog = self._mlog_scaler.transform(X)
        X_new = self._normalizer.transform(X_mlog)
        return X_new

    def inverse_transform(self, X):

        '''
        X   :   The data that will be inverse min-max scaled then inverse mirror-log transformed.
        '''

        X_mlog = self._normalizer.inverse_transform(X)
        X_inv = self._mlog_scaler.inverse_transform(X_mlog)
        return X_inv


class ProcessingPipeline(RegressorMixin, BaseEstimator):

    '''
    rfecv_kwargs        :   Keyword arguments for the RFECV feature selection step. Estimator for feature importance must be provided. Default is a LGBM regressor with 3-fold CV and step size of 2.
    scaler              :   Scaler for feature normalization. Default is MinMaxScaler.
    estimator           :   Estimator for the regression task. Default is a LGBM regressor.
    target_transformer  :   Transformer (or scaler) for the target variable. If set to 'ignore', no transformation is applied. Default is MirrorLogNormScaler. Transformer must implement fit, transform, and inverse_transform methods.
    '''

    def __init__(self, rfecv_kwargs:dict=None, scaler=None, estimator=None, target_transformer=None):

        self.rfecv_kwargs = rfecv_kwargs
        self.scaler = scaler
        self.estimator = estimator
        self.target_transformer = target_transformer

        rfecv_kwargs = self.rfecv_kwargs or {'estimator':lgb.LGBMRegressor(verbose=-1), 'cv':3, 'step':2}
        scaler_ = self.scaler or MinMaxScaler()
        estimator_ = self.estimator or lgb.LGBMRegressor(verbose=-1)
        target_transformer_ = self.target_transformer or MirrorLogNormScaler()

        if self.rfecv_kwargs in (None, False, 'ignore', 'skip'):
            feature_step = ('feature_elimination', 'passthrough')
        else:
            feature_step = ('feature_elimination', RFECV(**self.rfecv_kwargs))

        pipe = Pipeline([
            ('feature_elimination', RFECV(**rfecv_kwargs)),
            ('normalization', scaler_),
            ('estimation', estimator_)
        ])

        if self.target_transformer != 'ignore':
            ttr_pipe = TransformedTargetRegressor(
                regressor=pipe,
                transformer=target_transformer_,
                check_inverse=False
            )
        else:
            ttr_pipe = None
        self.model = ttr_pipe if ttr_pipe else pipe

    def fit(self, X, y):

        '''
        X   :   Training matrix.
        y   :   Target values.
        '''

        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            self.model.fit(X, y)
        return self

    def predict(self, X):

        '''
        X   :   Samples.
        '''

        with warnings.catch_warnings():
            warnings.simplefilter('ignore')
            return self.model.predict(X)

def willmotts_index(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    wi = 1 - (np.sum((y_true-y_pred)**2) / np.sum((np.abs(y_pred-np.mean(y_true))+(np.abs(y_true-np.mean(y_pred))))**2))
    return wi

def nash_sutcliffe_efficiency(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    ns = 1 - np.sum((y_true-y_pred)**2) / np.sum((y_true-np.mean(y_true))**2)
    return ns

def legates_mccabes_index(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    lm = 1 - np.sum(np.abs(y_pred-y_true)) / np.sum(np.abs(y_true-np.mean(y_true)))
    return lm

def kling_gupta_efficiency(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    cv_true = np.std(y_true) / np.mean(y_true)
    cv_pred = np.std(y_pred) / np.mean(y_pred)
    r = np.sum((y_true - y_true.mean()) * (y_pred - y_pred.mean())) / np.sqrt(np.sum((y_true - y_true.mean())**2) * np.sum((y_pred - y_pred.mean())**2))
    kge = 1 - np.sqrt((r-1)**2 + (np.mean(y_pred)/np.mean(y_true) - 1)**2 + (cv_pred/cv_true)**2)
    return kge

def normalized_root_mean_squared_error(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    nrmse = root_mean_squared_error(y_true=y_true, y_pred=y_pred) / np.mean(y_true)
    return nrmse

def relative_mean_absolute_percentage_error(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    rmae = mean_absolute_error(y_true=y_true, y_pred=y_pred) / np.mean(y_true)
    return rmae

def symmetric_mean_absolute_percentage_error(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    smape = (1/len(y_true)) * np.sum(np.abs(y_true-y_pred) / ((np.abs(y_true) + np.abs(y_pred))/2))
    return smape

def theils_inequality_coefficient(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    n = len(y_true)
    numerator = np.sqrt((1/n) * (np.sum(y_pred-y_true)**2))
    denominator = np.sqrt((1/n) * np.sum(y_true**2)) + np.sqrt((1/n) * np.sum(y_pred**2))
    tic = numerator / denominator
    return tic

def absolute_percentage_bias(y_true, y_pred):
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
    apb = np.abs(np.sum(y_true-y_pred) / np.sum(y_true))
    return apb

def evaluate_model(model, X, y_true) -> pd.DataFrame:
    '''
    model   :   A pre-trained model object.
    X       :   Feature matrix. Should be in the format your model object requires.
    y_true  :   True target array for prediction evaluation.
    '''

    if hasattr(model, 'predict'):
        y_pred = model.predict(X)
    elif callable(model):
        y_pred = model(X)
    else:
        raise TypeError('Model must be callable or have a .predict() method.')

    abbr = ['rmse', 'nrmse']
    prop = ['bias', 'bias']
    metrics = [root_mean_squared_error, normalized_root_mean_squared_error]

    results = [metric(y_true=y_true, y_pred=y_pred) for metric in metrics]

    df = pd.DataFrame(
        data=list(zip(prop, abbr, results)),
        columns=['property', 'metric', 'score']
    )

    return df

In [4]:
# Replace 'your_file_path.csv' with the actual path to your CSV file in Google Drive
csv_file_path = '/content/drive/MyDrive/MURES/rfe_dataset_2019_2025.csv'
df_rfe = pd.read_csv(csv_file_path)

# Setting Index
df_rfe['datetime'] = pd.to_datetime(df_rfe['datetime'], utc=True)
df_rfe = df_rfe.set_index('datetime')

y = df_rfe['price']
X_lag = df_rfe.drop(columns=['price'])

nrmse_scorer = make_scorer(normalized_root_mean_squared_error, greater_is_better=False)

In [5]:
# Removing NA values
df_xy = X_lag.copy()
df_xy["__y__"] = y
df_xy = df_xy.dropna()

y_clean = df_xy["__y__"]
X_clean = df_xy.drop(columns="__y__")

# Split the Data into Train and Test
X_train_val, X_test, y_train_val, y_test = train_test_split(X_clean, y_clean, test_size=0.1, shuffle=False)

train_size = int(len(X_train_val) * (0.9*0.8))  # 0.9 because train needs to be 80% of train/val dataset & validation shoudld be 90% of total dataset
step_size = 24*7*20  # every fold is 20 weeks in length
n_splits = (len(X_train_val) - train_size) // step_size
tscv = TimeSeriesSplit(n_splits=n_splits, max_train_size=train_size)

def _fit_supports(argname, estimator):
    """Check if the estimator.fit() method supports a given argument name."""
    sig = inspect.signature(estimator.fit)
    return argname in sig.parameters

In [6]:
## Hyperparameter tuning optimization using Optuna

def objective(trial):

    # XGBoost parameter
    params = {
        "max_depth": trial.suggest_int("max_depth", 3, 10),
        "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
        "reg_alpha": trial.suggest_categorical("reg_alpha", [0.0, 1e-8, 1e-6, 1e-4, 1e-3]),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-2, 10.0, log=True),
    }

    # Cross validation on each trial + Calculate with early stopping method applied
    fold_scores = []
    for fold, (tr_idx, va_idx) in enumerate(tscv.split(X_train_val, y_train_val)):
        Xtr, Xva = X_train_val.iloc[tr_idx], X_train_val.iloc[va_idx]
        ytr, yva = y_train_val.iloc[tr_idx], y_train_val.iloc[va_idx]

        model = XGBRegressor(
            n_estimators=300,
            tree_method='hist',
            random_state=42,
            n_jobs= 1,
            objective='reg:squarederror',
            eval_metric='rmse',
            **params
        )

        fit_kwargs = dict(
            X=Xtr, y=ytr,
            eval_set=[(Xva, yva)],
            verbose=False
        )

        # EarlyStopping: Prioritize callbacks, if not use early_stopping_rounds
        if _fit_supports("callbacks", model):
            from xgboost.callback import EarlyStopping
            fit_kwargs["callbacks"] = [EarlyStopping(rounds=100, save_best=True, maximize=False)]
        elif _fit_supports("early_stopping_rounds", model):
            fit_kwargs["early_stopping_rounds"] = 100

        model.fit(**fit_kwargs)

        # Using nrmse_scorer to calculate the performance on each fold
        score = nrmse_scorer(model, Xva, yva) if callable(getattr(nrmse_scorer, '__call__', None)) else float('nan')
        fold_scores.append(score)

        trial.report(float(np.nanmean(fold_scores)), step=fold)
        if trial.should_prune():
            raise optuna.TrialPruned()

    return float(np.nanmean(fold_scores))

# TPE + Hyperband Pruner
study = optuna.create_study(
    direction='maximize',  # better when score is higher
    sampler=optuna.samplers.TPESampler(seed=391),
    pruner=optuna.pruners.HyperbandPruner()
)

# Optimization
study.optimize(objective, n_trials=256, n_jobs=16)

print("[Optuna] Best score:", study.best_value)
print("[Optuna] Best params:", study.best_params)

best_params = study.best_params
best_score = study.best_value

# Final Model training using best parameters
final_model = XGBRegressor(
    n_estimators=1000,
    tree_method='hist',
    random_state=42,
    n_jobs=-1,
    objective='reg:squarederror',
    eval_metric='rmse',
    **best_params
)

split = int(len(X_train_val) * 0.9)
fit_kwargs = dict(
    X=X_train_val.iloc[:split], y=y_train_val.iloc[:split],
    eval_set=[(X_train_val.iloc[split:], y_train_val.iloc[split:])],
    verbose=False
)
if _fit_supports("callbacks", final_model):
    from xgboost.callback import EarlyStopping
    fit_kwargs["callbacks"] = [EarlyStopping(rounds=100, save_best=True, maximize=False)]
elif _fit_supports("early_stopping_rounds", final_model):
    fit_kwargs["early_stopping_rounds"] = 100

final_model.fit(**fit_kwargs)

class SearchLike:
    best_estimator_ = final_model
    best_params_    = best_params
    best_score_     = best_score
    study_          = study

search_es = SearchLike()
print("BEST:", search_es.best_score_, search_es.best_params_)

[I 2025-11-18 02:30:03,122] A new study created in memory with name: no-name-a81234fe-e25e-44ef-91c7-b4f5f85ef273
[I 2025-11-18 02:31:36,509] Trial 10 finished with value: -0.5504652835960462 and parameters: {'max_depth': 4, 'learning_rate': 0.046558210275273286, 'subsample': 0.8406346516186562, 'colsample_bytree': 0.6695069375568733, 'min_child_weight': 10, 'reg_alpha': 0.0001, 'reg_lambda': 0.4368268083658835}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:32:12,577] Trial 2 finished with value: -0.5519276721080127 and parameters: {'max_depth': 5, 'learning_rate': 0.036129831809019165, 'subsample': 0.9112576295481863, 'colsample_bytree': 0.9650772772286571, 'min_child_weight': 5, 'reg_alpha': 0.0001, 'reg_lambda': 0.06007785717571588}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:32:19,712] Trial 8 finished with value: -0.5792811354296296 and parameters: {'max_depth': 5, 'learning_rate': 0.004937810479975996, 'subsample': 0.9598491834664032, 'colsample_bytree': 0.8240060521512509, 'min_child_weight': 9, 'reg_alpha': 1e-08, 'reg_lambda': 0.055106664241804174}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:32:21,554] Trial 12 finished with value: -0.6758828662383305 and parameters: {'max_depth': 5, 'learning_rate': 0.0011757819000709393, 'subsample': 0.6556945167996963, 'colsample_bytree': 0.7678963153650469, 'min_child_weight': 2, 'reg_alpha': 0.0, 'reg_lambda': 0.054410554665844504}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:32:21,969] Trial 13 finished with value: -0.5836770468157301 and parameters: {'max_depth': 5, 'learning_rate': 0.004600660585195885, 'subsample': 0.6980311720756526, 'colsample_bytree': 0.8735282174129192, 'min_child_weight': 10, 'reg_alpha': 1e-06, 'reg_lambda': 1.2921515952728673}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:32:28,025] Trial 4 finished with value: -0.5561763740195236 and parameters: {'max_depth': 6, 'learning_rate': 0.05967783587922472, 'subsample': 0.9860098639036453, 'colsample_bytree': 0.6935336156470877, 'min_child_weight': 6, 'reg_alpha': 1e-06, 'reg_lambda': 0.6158826513849492}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:32:30,857] Trial 15 pruned.
[I 2025-11-18 02:32:54,712] Trial 11 finished with value: -0.5598311578616674 and parameters: {'max_depth': 6, 'learning_rate': 0.012633723815130525, 'subsample': 0.7916850551347602, 'colsample_bytree': 0.7916664171670188, 'min_child_weight': 5, 'reg_alpha': 1e-06, 'reg_lambda': 1.4548243338440596}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:32:55,852] Trial 14 finished with value: -0.5815874385940017 and parameters: {'max_depth': 7, 'learning_rate': 0.21861226772719433, 'subsample': 0.8963955775413006, 'colsample_bytree': 0.7232865158505444, 'min_child_weight': 10, 'reg_alpha': 1e-06, 'reg_lambda': 0.09198511812973251}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:33:16,893] Trial 0 pruned.
[I 2025-11-18 02:33:19,190] Trial 7 finished with value: -0.6223089743643268 and parameters: {'max_depth': 6, 'learning_rate': 0.0024662652459915154, 'subsample': 0.6442312859475986, 'colsample_bytree': 0.9461612795494087, 'min_child_weight': 8, 'reg_alpha': 1e-08, 'reg_lambda': 0.032641167268713175}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:33:34,115] Trial 16 finished with value: -0.5526032033633803 and parameters: {'max_depth': 5, 'learning_rate': 0.021211744772624, 'subsample': 0.8360982379449735, 'colsample_bytree': 0.8863364981603337, 'min_child_weight': 5, 'reg_alpha': 0.001, 'reg_lambda': 9.54510569344914}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:34:00,235] Trial 22 pruned.
[I 2025-11-18 02:34:02,714] Trial 18 pruned.
[I 2025-11-18 02:34:12,577] Trial 6 finished with value: -0.5557929822376689 and parameters: {'max_depth': 7, 'learning_rate': 0.017066367740649784, 'subsample': 0.6382457268109544, 'colsample_bytree': 0.9757500795711951, 'min_child_weight': 5, 'reg_alpha': 1e-08, 'reg_lambda': 0.06354217752396274}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:34:20,036] Trial 17 finished with value: -0.5679324172044006 and parameters: {'max_depth': 6, 'learning_rate': 0.14909014881933336, 'subsample': 0.892538486730716, 'colsample_bytree': 0.6083656931077205, 'min_child_weight': 7, 'reg_alpha': 1e-06, 'reg_lambda': 0.017150589590903577}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:34:24,444] Trial 1 finished with value: -0.576300108554144 and parameters: {'max_depth': 7, 'learning_rate': 0.014022809386636487, 'subsample': 0.6458062438912564, 'colsample_bytree': 0.7747598782667626, 'min_child_weight': 1, 'reg_alpha': 1e-06, 'reg_lambda': 0.30640571150276186}. Best is trial 10 with value: -0.5504652835960462.
[I 2025-11-18 02:34:30,057] Trial 26 finished with value: -0.543877742507136 and parameters: {'max_depth': 3, 'learning_rate': 0.039336344350965356, 'subsample': 0.8387649423740722, 'colsample_bytree': 0.6187296892447154, 'min_child_weight': 7, 'reg_alpha': 0.0001, 'reg_lambda': 0.011489952506088481}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:34:31,398] Trial 25 finished with value: -0.5469450789143748 and parameters: {'max_depth': 3, 'learning_rate': 0.015356107439197452, 'subsample': 0.8144048942757005, 'colsample_bytree': 0.6030647215594798, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.010137890348746854}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:34:38,175] Trial 5 finished with value: -0.5732581215035829 and parameters: {'max_depth': 8, 'learning_rate': 0.1306769135399548, 'subsample': 0.7328699511052832, 'colsample_bytree': 0.8646967860449709, 'min_child_weight': 6, 'reg_alpha': 0.001, 'reg_lambda': 0.061322530517838876}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:34:40,007] Trial 9 finished with value: -0.5613618644624813 and parameters: {'max_depth': 8, 'learning_rate': 0.09441515581437958, 'subsample': 0.8916418414413101, 'colsample_bytree': 0.8511189818655764, 'min_child_weight': 6, 'reg_alpha': 1e-08, 'reg_lambda': 0.09784609104178141}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:34:45,429] Trial 27 finished with value: -0.5466675493286002 and parameters: {'max_depth': 3, 'learning_rate': 0.06474029255664797, 'subsample': 0.831245444711932, 'colsample_bytree': 0.6097812275278112, 'min_child_weight': 7, 'reg_alpha': 0.0001, 'reg_lambda': 0.013613853053971935}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:35:08,830] Trial 28 finished with value: -0.5478300616952452 and parameters: {'max_depth': 3, 'learning_rate': 0.05869616529819647, 'subsample': 0.7971418423722914, 'colsample_bytree': 0.6189808338939887, 'min_child_weight': 7, 'reg_alpha': 0.0001, 'reg_lambda': 0.010623306776663463}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:35:09,494] Trial 32 pruned.
[I 2025-11-18 02:35:13,161] Trial 33 pruned.
[I 2025-11-18 02:35:13,228] Trial 29 finished with value: -0.5479472956735322 and parameters: {'max_depth': 3, 'learning_rate': 0.064762043877153, 'subsample': 0.8010109690227685, 'colsample_bytree': 0.6101074746352131, 'min_child_weight': 8, 'reg_alpha': 0.0001, 'reg_lambda': 0.012529696626059144}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:35:22,277] Trial 30 finished with value: -0.5455094404538083 and parameters: {'max_depth': 3, 'learning_rate': 0.07387911713691592, 'subsample': 0.8154598326327013, 'colsample_bytree': 0.6241434318573738, 'min_child_weight': 7, 'reg_alpha': 0.0001, 'reg_lambda': 0.015664654102951606}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:35:34,489] Trial 31 finished with value: -0.5465326111675635 and parameters: {'max_depth': 3, 'learning_rate': 0.051828775797684926, 'subsample': 0.787703528094376, 'colsample_bytree': 0.8817784330955799, 'min_child_weight': 8, 'reg_alpha': 0.0001, 'reg_lambda': 0.21688956628034253}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:35:40,848] Trial 34 finished with value: -0.5551684267122962 and parameters: {'max_depth': 3, 'learning_rate': 0.10979334828921881, 'subsample': 0.7553614743927075, 'colsample_bytree': 0.6368681225831718, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.01865708650201062}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:35:45,275] Trial 35 finished with value: -0.5526410094416887 and parameters: {'max_depth': 3, 'learning_rate': 0.0894060791812429, 'subsample': 0.7736734999107399, 'colsample_bytree': 0.6408620903029186, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.01253726202182859}. Best is trial 26 with value: -0.543877742507136.
[I 2025-11-18 02:35:50,344] Trial 36 finished with value: -0.54185276937153 and parameters: {'max_depth': 3, 'learning_rate': 0.03776295475657612, 'subsample': 0.8222445980308186, 'colsample_bytree': 0.6532018960862452, 'min_child_weight': 8, 'reg_alpha': 0.0001, 'reg_lambda': 0.01154325348334622}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:35:56,195] Trial 37 finished with value: -0.5429817884486058 and parameters: {'max_depth': 3, 'learning_rate': 0.032799548110016286, 'subsample': 0.7873771086468108, 'colsample_bytree': 0.633879486295708, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.011300758808508844}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:36:20,957] Trial 38 finished with value: -0.5419883358623809 and parameters: {'max_depth': 3, 'learning_rate': 0.028133915457575875, 'subsample': 0.7512524199429552, 'colsample_bytree': 0.6477986276372156, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.02032521867511508}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:36:21,777] Trial 39 finished with value: -0.5437973456713339 and parameters: {'max_depth': 3, 'learning_rate': 0.028318251555123186, 'subsample': 0.8412929806453072, 'colsample_bytree': 0.6396960827386218, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.020948896668733355}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:36:39,060] Trial 44 pruned.
[I 2025-11-18 02:36:52,074] Trial 42 finished with value: -0.5428245843535691 and parameters: {'max_depth': 4, 'learning_rate': 0.031212520230016968, 'subsample': 0.7553628883007312, 'colsample_bytree': 0.7214844025136801, 'min_child_weight': 9, 'reg_alpha': 0.0001, 'reg_lambda': 0.02370449287982941}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:37:05,054] Trial 20 pruned.
[I 2025-11-18 02:37:17,495] Trial 45 finished with value: -0.5831503493772553 and parameters: {'max_depth': 4, 'learning_rate': 0.29588489656710343, 'subsample': 0.8585184617714197, 'colsample_bytree': 0.7234455502077306, 'min_child_weight': 9, 'reg_alpha': 0.0001, 'reg_lambda': 0.027381596313425505}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:37:22,185] Trial 19 finished with value: -0.5701158315692091 and parameters: {'max_depth': 9, 'learning_rate': 0.2862768941381552, 'subsample': 0.9129504647942176, 'colsample_bytree': 0.8136145768302799, 'min_child_weight': 10, 'reg_alpha': 0.0001, 'reg_lambda': 4.856290627384292}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:37:42,671] Trial 50 pruned.
[I 2025-11-18 02:37:57,356] Trial 23 pruned.
[I 2025-11-18 02:37:57,532] Trial 49 finished with value: -0.5462660488168833 and parameters: {'max_depth': 4, 'learning_rate': 0.02674743807562309, 'subsample': 0.859951338265547, 'colsample_bytree': 0.7018731013268126, 'min_child_weight': 9, 'reg_alpha': 0.001, 'reg_lambda': 0.02856488964152457}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:38:45,460] Trial 3 finished with value: -0.5676990304343665 and parameters: {'max_depth': 10, 'learning_rate': 0.03761952850842749, 'subsample': 0.729766755408779, 'colsample_bytree': 0.9690713570892653, 'min_child_weight': 6, 'reg_alpha': 0.0001, 'reg_lambda': 4.488198798242046}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:38:49,939] Trial 57 pruned.
[I 2025-11-18 02:38:53,855] Trial 54 finished with value: -0.5541817490797906 and parameters: {'max_depth': 4, 'learning_rate': 0.010417652766262242, 'subsample': 0.7293693288237584, 'colsample_bytree': 0.6885766459750179, 'min_child_weight': 9, 'reg_alpha': 0.001, 'reg_lambda': 0.02555174751574828}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:39:08,196] Trial 55 finished with value: -0.5458270808224867 and parameters: {'max_depth': 4, 'learning_rate': 0.026072477587373254, 'subsample': 0.6916301891220604, 'colsample_bytree': 0.6873980062233592, 'min_child_weight': 9, 'reg_alpha': 0.0, 'reg_lambda': 0.03896641178813301}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:39:22,250] Trial 56 finished with value: -0.5451242600735251 and parameters: {'max_depth': 4, 'learning_rate': 0.0301879867797234, 'subsample': 0.702797750449092, 'colsample_bytree': 0.670839767263953, 'min_child_weight': 9, 'reg_alpha': 0.001, 'reg_lambda': 0.042092936593088125}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:39:33,808] Trial 40 pruned.
[I 2025-11-18 02:39:35,404] Trial 24 finished with value: -0.5765461272321192 and parameters: {'max_depth': 10, 'learning_rate': 0.12349589794104668, 'subsample': 0.8623280637789341, 'colsample_bytree': 0.6775248211430264, 'min_child_weight': 6, 'reg_alpha': 0.0, 'reg_lambda': 0.6041621274850048}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:39:39,390] Trial 43 pruned.
[I 2025-11-18 02:39:41,143] Trial 41 pruned.
[I 2025-11-18 02:40:03,282] Trial 61 pruned.
[I 2025-11-18 02:40:11,961] Trial 58 finished with value: -0.5422868023181949 and parameters: {'max_depth': 4, 'learning_rate': 0.03308754186643012, 'subsample': 0.7013621648137855, 'colsample_bytree': 0.7516437015373656, 'min_child_weight': 9, 'reg_alpha': 0.001, 'reg_lambda': 0.04041254867252885}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:40:13,308] Trial 21 pruned.
[I 2025-11-18 02:40:16,809] Trial 47 pruned.
[I 2025-11-18 02:40:17,979] Trial 63 pruned.
[I 2025-11-18 02:40:18,459] Trial 59 finished with value: -0.5444880879037255 and parameters: {'max_depth': 4, 'learning_rate': 0.019863323311075157, 'subsample': 0.7102404138625441, 'colsample_bytree': 0.7521479616557329, 'min_child_weight': 9, 'reg_alpha': 0.0, 'reg_lambda': 0.04091034746331599}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:40:21,507] Trial 60 finished with value: -0.543904323582111 and parameters: {'max_depth': 4, 'learning_rate': 0.0213494708166421, 'subsample': 0.7553700596036583, 'colsample_bytree': 0.7480378625785633, 'min_child_weight': 9, 'reg_alpha': 0.0, 'reg_lambda': 0.038001508018994976}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:40:22,232] Trial 48 pruned.
[I 2025-11-18 02:40:25,009] Trial 66 pruned.
[I 2025-11-18 02:40:35,122] Trial 62 finished with value: -0.5501196340252564 and parameters: {'max_depth': 3, 'learning_rate': 0.01910729328454001, 'subsample': 0.7582509828347456, 'colsample_bytree': 0.7573133684461237, 'min_child_weight': 4, 'reg_alpha': 1e-08, 'reg_lambda': 0.019578452595281397}. Best is trial 36 with value: -0.54185276937153.
[I 2025-11-18 02:40:47,171] Trial 64 pruned.
[I 2025-11-18 02:41:13,054] Trial 67 finished with value: -0.5417111077889768 and parameters: {'max_depth': 3, 'learning_rate': 0.042945716604305906, 'subsample': 0.8155838232209114, 'colsample_bytree': 0.6287221627529829, 'min_child_weight': 7, 'reg_alpha': 1e-08, 'reg_lambda': 0.016183381556271012}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:41:17,873] Trial 51 pruned.
[I 2025-11-18 02:41:20,937] Trial 72 pruned.
[I 2025-11-18 02:41:24,274] Trial 71 pruned.
[I 2025-11-18 02:41:24,613] Trial 68 finished with value: -0.5423184882217295 and parameters: {'max_depth': 3, 'learning_rate': 0.04078359929231202, 'subsample': 0.7529373858881873, 'colsample_bytree': 0.7592123152593018, 'min_child_weight': 10, 'reg_alpha': 0.001, 'reg_lambda': 0.017092255709854957}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:41:28,272] Trial 65 finished with value: -0.5564820409536486 and parameters: {'max_depth': 5, 'learning_rate': 0.018573580584867095, 'subsample': 0.8157902568862183, 'colsample_bytree': 0.6499021001762093, 'min_child_weight': 4, 'reg_alpha': 0.001, 'reg_lambda': 0.019216344916221522}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:41:55,999] Trial 69 finished with value: -0.5495326460473445 and parameters: {'max_depth': 5, 'learning_rate': 0.041587375941067775, 'subsample': 0.6690591706370478, 'colsample_bytree': 0.7531193493625813, 'min_child_weight': 10, 'reg_alpha': 0.001, 'reg_lambda': 0.06989628317470219}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:41:57,100] Trial 77 finished with value: -0.5431350129441376 and parameters: {'max_depth': 3, 'learning_rate': 0.038510713382615844, 'subsample': 0.6737193628350745, 'colsample_bytree': 0.630805920770428, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.06297707449089303}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:41:59,998] Trial 74 finished with value: -0.5532010534986923 and parameters: {'max_depth': 5, 'learning_rate': 0.03872651089215369, 'subsample': 0.8169674875709658, 'colsample_bytree': 0.6387534162143885, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.07189842647055575}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:42:07,350] Trial 70 finished with value: -0.5455242676267673 and parameters: {'max_depth': 5, 'learning_rate': 0.018532844479130554, 'subsample': 0.673712418913575, 'colsample_bytree': 0.7621473727184858, 'min_child_weight': 10, 'reg_alpha': 0.001, 'reg_lambda': 0.07229234626119882}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:42:08,273] Trial 82 pruned.
[I 2025-11-18 02:42:13,094] Trial 75 finished with value: -0.5537219613679184 and parameters: {'max_depth': 5, 'learning_rate': 0.013521854460838522, 'subsample': 0.8156208800628312, 'colsample_bytree': 0.6340815054327011, 'min_child_weight': 10, 'reg_alpha': 0.001, 'reg_lambda': 0.06380006317359053}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:42:18,051] Trial 76 finished with value: -0.553428813567115 and parameters: {'max_depth': 5, 'learning_rate': 0.038637119624348605, 'subsample': 0.8169580693828234, 'colsample_bytree': 0.6238325026992093, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.013342869981737483}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:42:24,425] Trial 73 finished with value: -0.5462597902044809 and parameters: {'max_depth': 5, 'learning_rate': 0.012537912671191722, 'subsample': 0.6764343980239391, 'colsample_bytree': 0.9990925705196214, 'min_child_weight': 10, 'reg_alpha': 0.001, 'reg_lambda': 0.07292623929567521}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:42:28,720] Trial 46 finished with value: -0.5632472758995167 and parameters: {'max_depth': 10, 'learning_rate': 0.026032558908390884, 'subsample': 0.8607323622608123, 'colsample_bytree': 0.7203941377491139, 'min_child_weight': 9, 'reg_alpha': 0.0001, 'reg_lambda': 0.025485894993316813}. Best is trial 67 with value: -0.5417111077889768.
[I 2025-11-18 02:42:33,634] Trial 80 finished with value: -0.541325907928306 and parameters: {'max_depth': 3, 'learning_rate': 0.03791037865231607, 'subsample': 0.8220066103558998, 'colsample_bytree': 0.7994023092367197, 'min_child_weight': 8, 'reg_alpha': 0.001, 'reg_lambda': 0.07603004948566022}. Best is trial 80 with value: -0.541325907928306.

[Optuna] Best score: -0.536529471308259
[Optuna] Best params: {'max_depth': 3, 'learning_rate': 0.04243714864677509, 'subsample': 0.6233752828875716, 'colsample_bytree': 0.9909653317759352, 'min_child_weight': 10, 'reg_alpha': 0.0, 'reg_lambda': 5.3877974642145645}
BEST: -0.536529471308259 {'max_depth': 3, 'learning_rate': 0.04243714864677509, 'subsample': 0.6233752828875716, 'colsample_bytree': 0.9909653317759352, 'min_child_weight': 10, 'reg_alpha': 0.0, 'reg_lambda': 5.3877974642145645}

In [7]:
evaluate_model(final_model, X_test, y_test)

  property metric      score
0     bias   rmse  44.787713
1     bias  nrmse   0.513999

In [12]:
from lightgbm import LGBMRegressor, early_stopping

## Hyperparameter tuning optimization using Optuna (LightGBM)

def objective(trial):

    # LightGBM parameters
    params = {
      "num_leaves": trial.suggest_int("num_leaves", 31, 255),
      "max_depth": trial.suggest_int("max_depth", -1, 16),
      "learning_rate": trial.suggest_float("learning_rate", 1e-3, 0.3, log=True),
      "subsample": trial.suggest_float("subsample", 0.6, 1.0),
      "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
      "min_child_samples": trial.suggest_int("min_child_samples", 10, 100),
      "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
      "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True),
    }

    # Cross validation on each trial + early stopping
    fold_scores = []
    for fold, (tr_idx, va_idx) in enumerate(tscv.split(X_train_val, y_train_val)):
        Xtr, Xva = X_train_val.iloc[tr_idx], X_train_val.iloc[va_idx]
        ytr, yva = y_train_val.iloc[tr_idx], y_train_val.iloc[va_idx]

        model = LGBMRegressor(
            n_estimators=1000,
            objective="regression",
            random_state=42,
            n_jobs=1,
            **params
        )

        fit_kwargs = dict(
            X=Xtr, y=ytr,
            eval_set=[(Xva, yva)],
            eval_metric="rmse",
        )

        # EarlyStopping
        if _fit_supports("callbacks", model):
            fit_kwargs["callbacks"] = [early_stopping(stopping_rounds=100)]
        elif _fit_supports("early_stopping_rounds", model):
            fit_kwargs["early_stopping_rounds"] = 100

        model.fit(**fit_kwargs)

        # Using nrmse_scorer to calculate the performance on each fold
        score = nrmse_scorer(model, Xva, yva) if callable(getattr(nrmse_scorer, '__call__', None)) else float('nan')
        fold_scores.append(score)

        trial.report(float(np.nanmean(fold_scores)), step=fold)
        if trial.should_prune():
            raise optuna.TrialPruned()

    return float(np.nanmean(fold_scores))


# TPE + Hyperband Pruner
study = optuna.create_study(
    direction='maximize',  # # better when score is higher
    sampler=optuna.samplers.TPESampler(seed=391),
    pruner=optuna.pruners.HyperbandPruner()
)

# Optimization
study.optimize(objective, n_trials=256, n_jobs=16)

print("[Optuna-LGBM] Best score:", study.best_value)
print("[Optuna-LGBM] Best params:", study.best_params)

best_params = study.best_params
best_score = study.best_value

# Final Model training using best parameters
final_model = LGBMRegressor(
    n_estimators=1500,
    objective="regression",
    random_state=42,
    n_jobs=-1,
    **best_params
)

split = int(len(X_train_val) * 0.9)
fit_kwargs = dict(
    X=X_train_val.iloc[:split], y=y_train_val.iloc[:split],
    eval_set=[(X_train_val.iloc[split:], y_train_val.iloc[split:])],
    eval_metric="rmse"
)
if _fit_supports("callbacks", final_model):
    fit_kwargs["callbacks"] = [early_stopping(stopping_rounds=100)]
elif _fit_supports("early_stopping_rounds", final_model):
    fit_kwargs["early_stopping_rounds"] = 100

final_model.fit(**fit_kwargs)

class SearchLike:
    best_estimator_ = final_model
    best_params_    = best_params
    best_score_     = best_score
    study_          = study

search_es = SearchLike()
print("BEST (LGBM):", search_es.best_score_, search_es.best_params_)

[I 2025-11-18 03:43:58,612] A new study created in memory with name: no-name-c2656475-edfa-4fb8-9427-fdaac457d862

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[56]	valid_0's rmse: 25.118	valid_0's l2: 630.913
Early stopping, best iteration is:
[280]	valid_0's rmse: 24.0082	valid_0's l2: 576.395
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[91]	valid_0's rmse: 157.957	valid_0's l2: 24950.5
Early stopping, best iteration is:
[469]	valid_0's rmse: 25.566	valid_0's l2: 653.623
Early stopping, best iteration is:
[251]	valid_0's rmse: 25.6736	valid_0's l2: 659.133
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[81]	valid_0's rmse: 32.5351	valid_0's l2: 1058.53
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 25.8361	valid_0's l2: 667.506
Early stopping, best iteration is:
[85]	valid_0's rmse: 26.1158	valid_0's l2: 682.037

[I 2025-11-18 03:44:26,558] Trial 5 finished with value: -0.5361159179311066 and parameters: {'num_leaves': 144, 'max_depth': 3, 'learning_rate': 0.19701548442573374, 'subsample': 0.9908716220668878, 'colsample_bytree': 0.8361441820623228, 'min_child_samples': 66, 'reg_alpha': 0.00031624192999828583, 'reg_lambda': 0.16581521932819143}. Best is trial 5 with value: -0.5361159179311066.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[64]	valid_0's rmse: 26.227	valid_0's l2: 687.853
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[989]	valid_0's rmse: 157.314	valid_0's l2: 24747.8
Early stopping, best iteration is:
[97]	valid_0's rmse: 26.3975	valid_0's l2: 696.826
Early stopping, best iteration is:
[347]	valid_0's rmse: 26.3355	valid_0's l2: 693.559
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:44:45,913] Trial 9 finished with value: -0.5362633875114955 and parameters: {'num_leaves': 190, 'max_depth': 1, 'learning_rate': 0.24416189051375015, 'subsample': 0.6555764665921484, 'colsample_bytree': 0.7570217342039128, 'min_child_samples': 92, 'reg_alpha': 0.0002281338808750599, 'reg_lambda': 0.038210243113972295}. Best is trial 5 with value: -0.5361159179311066.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.7398	valid_0's l2: 1206.85
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[142]	valid_0's rmse: 26.5948	valid_0's l2: 707.284
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[564]	valid_0's rmse: 157.27	valid_0's l2: 24733.8
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 157.811	valid_0's l2: 24904.4
Early stopping, best iteration is:
[74]	valid_0's rmse: 26.6316	valid_0's l2: 709.244
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 162.864	valid_0's l2: 26524.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:45:17,056] Trial 3 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[552]	valid_0's rmse: 26.1317	valid_0's l2: 682.866
Early stopping, best iteration is:
[124]	valid_0's rmse: 156.701	valid_0's l2: 24555.3
Early stopping, best iteration is:
[245]	valid_0's rmse: 26.1998	valid_0's l2: 686.429

[I 2025-11-18 03:45:29,202] Trial 7 pruned.

Early stopping, best iteration is:
[289]	valid_0's rmse: 157.821	valid_0's l2: 24907.6
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:45:33,743] Trial 0 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[182]	valid_0's rmse: 159.774	valid_0's l2: 25527.9
Early stopping, best iteration is:
[230]	valid_0's rmse: 32.6701	valid_0's l2: 1067.34
Did not meet early stopping. Best iteration is:
[920]	valid_0's rmse: 26.2065	valid_0's l2: 686.779

[I 2025-11-18 03:45:41,429] Trial 11 finished with value: -0.5392660205186234 and parameters: {'num_leaves': 146, 'max_depth': 5, 'learning_rate': 0.023876247395808195, 'subsample': 0.7107253733823052, 'colsample_bytree': 0.8550755067266614, 'min_child_samples': 62, 'reg_alpha': 0.09007615280422068, 'reg_lambda': 2.8153027264068586}. Best is trial 5 with value: -0.5361159179311066.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 24.3667	valid_0's l2: 593.734
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[227]	valid_0's rmse: 25.8014	valid_0's l2: 665.711
Early stopping, best iteration is:
[524]	valid_0's rmse: 32.4824	valid_0's l2: 1055.11
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:45:50,583] Trial 6 finished with value: -0.5386625655230413 and parameters: {'num_leaves': 57, 'max_depth': 3, 'learning_rate': 0.02129717167441583, 'subsample': 0.8174119805571096, 'colsample_bytree': 0.8097629673598116, 'min_child_samples': 46, 'reg_alpha': 0.001464696844682622, 'reg_lambda': 0.04115989507101676}. Best is trial 5 with value: -0.5361159179311066.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[246]	valid_0's rmse: 162.263	valid_0's l2: 26329.3
Early stopping, best iteration is:
[80]	valid_0's rmse: 26.1043	valid_0's l2: 681.437
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 26.3359	valid_0's l2: 693.579
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 27.0468	valid_0's l2: 731.53
Early stopping, best iteration is:
[28]	valid_0's rmse: 156.503	valid_0's l2: 24493.2

[I 2025-11-18 03:46:12,278] Trial 21 pruned.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 154.996	valid_0's l2: 24023.8
Early stopping, best iteration is:
[74]	valid_0's rmse: 25.7788	valid_0's l2: 664.546
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[191]	valid_0's rmse: 33.3302	valid_0's l2: 1110.91
Early stopping, best iteration is:
[198]	valid_0's rmse: 32.3428	valid_0's l2: 1046.06

[I 2025-11-18 03:46:28,337] Trial 19 finished with value: -0.5296263135086101 and parameters: {'num_leaves': 192, 'max_depth': 1, 'learning_rate': 0.06138121402333371, 'subsample': 0.9625163277679827, 'colsample_bytree': 0.7695610978432316, 'min_child_samples': 42, 'reg_alpha': 0.02616424735544612, 'reg_lambda': 2.351882470672208}. Best is trial 19 with value: -0.5296263135086101.
[I 2025-11-18 03:46:29,660] Trial 16 finished with value: -0.5479850366215017 and parameters: {'num_leaves': 54, 'max_depth': 8, 'learning_rate': 0.03574656869320226, 'subsample': 0.8380652798465781, 'colsample_bytree': 0.9822886096077124, 'min_child_samples': 11, 'reg_alpha': 2.4262957293073807e-06, 'reg_lambda': 0.26206514413341814}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 26.7388	valid_0's l2: 714.963
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[161]	valid_0's rmse: 158.621	valid_0's l2: 25160.7
Early stopping, best iteration is:
[117]	valid_0's rmse: 162.011	valid_0's l2: 26247.4
Early stopping, best iteration is:
[814]	valid_0's rmse: 161.34	valid_0's l2: 26030.7

[I 2025-11-18 03:46:39,229] Trial 8 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 27.2084	valid_0's l2: 740.298
Early stopping, best iteration is:
[506]	valid_0's rmse: 158.905	valid_0's l2: 25250.8
Early stopping, best iteration is:
[122]	valid_0's rmse: 26.1631	valid_0's l2: 684.509
Early stopping, best iteration is:
[66]	valid_0's rmse: 25.5448	valid_0's l2: 652.538
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[83]	valid_0's rmse: 32.4121	valid_0's l2: 1050.54

[I 2025-11-18 03:46:52,213] Trial 23 finished with value: -0.5410535898506538 and parameters: {'num_leaves': 104, 'max_depth': 4, 'learning_rate': 0.1022954237179183, 'subsample': 0.6287846330913726, 'colsample_bytree': 0.8930236834225849, 'min_child_samples': 91, 'reg_alpha': 4.968413609266534, 'reg_lambda': 2.0111227136636582}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:46:57,463] Trial 4 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[222]	valid_0's rmse: 159.587	valid_0's l2: 25468.1
Early stopping, best iteration is:
[30]	valid_0's rmse: 157.704	valid_0's l2: 24870.7
Early stopping, best iteration is:
[131]	valid_0's rmse: 158.084	valid_0's l2: 24990.4
Early stopping, best iteration is:
[183]	valid_0's rmse: 33.3598	valid_0's l2: 1112.88
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 27.0882	valid_0's l2: 733.771
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:47:07,676] Trial 14 finished with value: -0.5544396231295304 and parameters: {'num_leaves': 152, 'max_depth': 0, 'learning_rate': 0.03925958112160008, 'subsample': 0.7185760136748236, 'colsample_bytree': 0.6125432783615251, 'min_child_samples': 24, 'reg_alpha': 9.412569199398585e-06, 'reg_lambda': 0.0010686781337858875}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[57]	valid_0's rmse: 25.7906	valid_0's l2: 665.155
Early stopping, best iteration is:
[66]	valid_0's rmse: 32.2579	valid_0's l2: 1040.57
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:47:18,058] Trial 26 finished with value: -0.5380752007480805 and parameters: {'num_leaves': 208, 'max_depth': 5, 'learning_rate': 0.10852141218553289, 'subsample': 0.9889628886950781, 'colsample_bytree': 0.7329162003936663, 'min_child_samples': 40, 'reg_alpha': 0.005640837574537777, 'reg_lambda': 9.061362156208727}. Best is trial 19 with value: -0.5296263135086101.

Early stopping, best iteration is:
[17]	valid_0's rmse: 35.045	valid_0's l2: 1228.15

[I 2025-11-18 03:47:19,165] Trial 24 finished with value: -0.5523534414878221 and parameters: {'num_leaves': 189, 'max_depth': 9, 'learning_rate': 0.2179332134714928, 'subsample': 0.6695321506302426, 'colsample_bytree': 0.6436683313849617, 'min_child_samples': 63, 'reg_alpha': 1.7946715119945605e-06, 'reg_lambda': 6.0814303705859825}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[28]	valid_0's rmse: 25.6236	valid_0's l2: 656.568
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[135]	valid_0's rmse: 156.659	valid_0's l2: 24542.1
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[28]	valid_0's rmse: 26.2107	valid_0's l2: 686.999
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[91]	valid_0's rmse: 32.7462	valid_0's l2: 1072.32

[I 2025-11-18 03:47:44,999] Trial 29 finished with value: -0.5393943211509447 and parameters: {'num_leaves': 207, 'max_depth': 5, 'learning_rate': 0.11236513747866247, 'subsample': 0.9987816542304028, 'colsample_bytree': 0.736913568273188, 'min_child_samples': 79, 'reg_alpha': 0.008789962077654917, 'reg_lambda': 8.89805165335566}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[91]	valid_0's rmse: 33.8308	valid_0's l2: 1144.52
Early stopping, best iteration is:
[436]	valid_0's rmse: 32.7459	valid_0's l2: 1072.29

[I 2025-11-18 03:47:53,185] Trial 20 finished with value: -0.5517198851094746 and parameters: {'num_leaves': 144, 'max_depth': 12, 'learning_rate': 0.027204216808926637, 'subsample': 0.812738068247121, 'colsample_bytree': 0.9425411430422712, 'min_child_samples': 90, 'reg_alpha': 3.8980778445918654e-07, 'reg_lambda': 0.351120844254996}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:47:57,815] Trial 18 finished with value: -0.5429297692469822 and parameters: {'num_leaves': 41, 'max_depth': 10, 'learning_rate': 0.018693125410101617, 'subsample': 0.8977834341680664, 'colsample_bytree': 0.7252472335656054, 'min_child_samples': 63, 'reg_alpha': 0.00835319148075453, 'reg_lambda': 5.760794881351109}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[41]	valid_0's rmse: 156.265	valid_0's l2: 24418.9
Early stopping, best iteration is:
[53]	valid_0's rmse: 156.919	valid_0's l2: 24623.7
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 158.873	valid_0's l2: 25240.6
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 27.7314	valid_0's l2: 769.028
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 27.8215	valid_0's l2: 774.034
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 28.0752	valid_0's l2: 788.218
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 26.3771	valid_0's l2: 695.75
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[19]	valid_0's rmse: 34.3951	valid_0's l2: 1183.02

[I 2025-11-18 03:48:31,300] Trial 30 finished with value: -0.5479403144855355 and parameters: {'num_leaves': 193, 'max_depth': 16, 'learning_rate': 0.12121363009183235, 'subsample': 0.9945377004278315, 'colsample_bytree': 0.7653116655562074, 'min_child_samples': 78, 'reg_alpha': 0.07614917462206337, 'reg_lambda': 0.3187616515397933}. Best is trial 19 with value: -0.5296263135086101.

Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 26.5453	valid_0's l2: 704.652

[I 2025-11-18 03:48:33,117] Trial 10 pruned.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 158.251	valid_0's l2: 25043.3
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[106]	valid_0's rmse: 25.3464	valid_0's l2: 642.438
Early stopping, best iteration is:
[426]	valid_0's rmse: 26.1753	valid_0's l2: 685.144
Early stopping, best iteration is:
[463]	valid_0's rmse: 158.203	valid_0's l2: 25028.2
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[16]	valid_0's rmse: 34.2843	valid_0's l2: 1175.41

[I 2025-11-18 03:48:45,917] Trial 28 finished with value: -0.5446231036675042 and parameters: {'num_leaves': 201, 'max_depth': -1, 'learning_rate': 0.12180271732275152, 'subsample': 0.9845318317441119, 'colsample_bytree': 0.741678725207105, 'min_child_samples': 80, 'reg_alpha': 0.0046002760161099, 'reg_lambda': 0.46755920323080447}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[172]	valid_0's rmse: 152.978	valid_0's l2: 23402.2
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 187.792	valid_0's l2: 35266
Early stopping, best iteration is:
[135]	valid_0's rmse: 24.6813	valid_0's l2: 609.164
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 187.09	valid_0's l2: 35002.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:48:55,407] Trial 33 pruned.
[I 2025-11-18 03:48:57,249] Trial 32 pruned.
[I 2025-11-18 03:48:58,014] Trial 1 pruned.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 189.82	valid_0's l2: 36031.8
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[62]	valid_0's rmse: 33.0118	valid_0's l2: 1089.78
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:49:00,016] Trial 36 finished with value: -0.5317886324330818 and parameters: {'num_leaves': 224, 'max_depth': 2, 'learning_rate': 0.18455956076447858, 'subsample': 0.7747936509492811, 'colsample_bytree': 0.7645817235178126, 'min_child_samples': 52, 'reg_alpha': 0.00020670529304429885, 'reg_lambda': 0.0144366999406347}. Best is trial 19 with value: -0.5296263135086101.
[I 2025-11-18 03:49:01,575] Trial 34 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[144]	valid_0's rmse: 158.151	valid_0's l2: 25011.8
Early stopping, best iteration is:
[110]	valid_0's rmse: 24.9519	valid_0's l2: 622.597
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[520]	valid_0's rmse: 24.0023	valid_0's l2: 576.112
Early stopping, best iteration is:
[30]	valid_0's rmse: 25.8359	valid_0's l2: 667.494
Early stopping, best iteration is:
[689]	valid_0's rmse: 23.9234	valid_0's l2: 572.331
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[64]	valid_0's rmse: 25.7778	valid_0's l2: 664.493
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 157.751	valid_0's l2: 24885.3
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 172.612	valid_0's l2: 29795
Early stopping, best iteration is:
[243]	valid_0's rmse: 32.7519	valid_0's l2: 1072.69

[I 2025-11-18 03:49:19,794] Trial 37 finished with value: -0.5343512066342063 and parameters: {'num_leaves': 237, 'max_depth': 2, 'learning_rate': 0.20449532809847162, 'subsample': 0.7755632874820975, 'colsample_bytree': 0.7793066539971351, 'min_child_samples': 99, 'reg_alpha': 0.00010766683174464777, 'reg_lambda': 0.011013295136109344}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[142]	valid_0's rmse: 157.009	valid_0's l2: 24651.9

[I 2025-11-18 03:49:32,453] Trial 41 pruned.

Did not meet early stopping. Best iteration is:
[974]	valid_0's rmse: 157.733	valid_0's l2: 24879.6

[I 2025-11-18 03:49:34,052] Trial 2 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[162]	valid_0's rmse: 156.923	valid_0's l2: 24624.9
Did not meet early stopping. Best iteration is:
[997]	valid_0's rmse: 157.722	valid_0's l2: 24876.1

[I 2025-11-18 03:49:36,041] Trial 42 pruned.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 170.722	valid_0's l2: 29145.9
Early stopping, best iteration is:
[411]	valid_0's rmse: 32.8472	valid_0's l2: 1078.94
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:49:39,368] Trial 38 finished with value: -0.5358987525994987 and parameters: {'num_leaves': 232, 'max_depth': 2, 'learning_rate': 0.19666333650862297, 'subsample': 0.7741009009070449, 'colsample_bytree': 0.8552803681539571, 'min_child_samples': 100, 'reg_alpha': 0.0001129952643776717, 'reg_lambda': 0.0106108540191424}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:49:45,217] Trial 40 finished with value: -0.5352292394879227 and parameters: {'num_leaves': 229, 'max_depth': 1, 'learning_rate': 0.19963487785617381, 'subsample': 0.8612927969847146, 'colsample_bytree': 0.6980503543775132, 'min_child_samples': 96, 'reg_alpha': 0.000392711223306939, 'reg_lambda': 0.0076191923637508345}. Best is trial 19 with value: -0.5296263135086101.

Early stopping, best iteration is:
[55]	valid_0's rmse: 34.4505	valid_0's l2: 1186.84

[I 2025-11-18 03:49:46,138] Trial 39 finished with value: -0.5352771715182326 and parameters: {'num_leaves': 231, 'max_depth': 1, 'learning_rate': 0.19006208969340482, 'subsample': 0.7844775949200993, 'colsample_bytree': 0.8533183371478155, 'min_child_samples': 96, 'reg_alpha': 0.00017406914336312614, 'reg_lambda': 0.011211687107484625}. Best is trial 19 with value: -0.5296263135086101.

Early stopping, best iteration is:
[51]	valid_0's rmse: 34.3316	valid_0's l2: 1178.66
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[51]	valid_0's rmse: 26.0639	valid_0's l2: 679.325
Early stopping, best iteration is:
[15]	valid_0's rmse: 26.115	valid_0's l2: 681.991
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[50]	valid_0's rmse: 25.9914	valid_0's l2: 675.55
Early stopping, best iteration is:
[62]	valid_0's rmse: 26.2499	valid_0's l2: 689.056
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[27]	valid_0's rmse: 25.9196	valid_0's l2: 671.823
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[38]	valid_0's rmse: 26.6742	valid_0's l2: 711.514
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[803]	valid_0's rmse: 26.5242	valid_0's l2: 703.532
Early stopping, best iteration is:
[42]	valid_0's rmse: 26.4165	valid_0's l2: 697.829
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[32]	valid_0's rmse: 160.501	valid_0's l2: 25760.6

[I 2025-11-18 03:50:27,321] Trial 46 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[76]	valid_0's rmse: 160.218	valid_0's l2: 25669.7
Early stopping, best iteration is:
[39]	valid_0's rmse: 159.152	valid_0's l2: 25329.5

[I 2025-11-18 03:50:40,485] Trial 48 pruned.

Did not meet early stopping. Best iteration is:
[968]	valid_0's rmse: 24.1439	valid_0's l2: 582.928
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 162.759	valid_0's l2: 26490.6
Early stopping, best iteration is:
[64]	valid_0's rmse: 160.3	valid_0's l2: 25696.2
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[205]	valid_0's rmse: 33.7414	valid_0's l2: 1138.48
Early stopping, best iteration is:
[871]	valid_0's rmse: 24.1662	valid_0's l2: 584.006
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:51:00,619] Trial 12 finished with value: -0.5483351091356808 and parameters: {'num_leaves': 255, 'max_depth': 12, 'learning_rate': 0.014322163426517785, 'subsample': 0.6387735251548005, 'colsample_bytree': 0.9347681716157047, 'min_child_samples': 23, 'reg_alpha': 2.3592337708878395e-08, 'reg_lambda': 0.42890359159675173}. Best is trial 19 with value: -0.5296263135086101.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[990]	valid_0's rmse: 154.959	valid_0's l2: 24012.4

[I 2025-11-18 03:51:05,315] Trial 27 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[98]	valid_0's rmse: 25.7922	valid_0's l2: 665.235
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 25.3342	valid_0's l2: 641.82
Early stopping, best iteration is:
[108]	valid_0's rmse: 158.371	valid_0's l2: 25081.5
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 33.7817	valid_0's l2: 1141.21

[I 2025-11-18 03:51:19,035] Trial 50 finished with value: -0.5298324399362971 and parameters: {'num_leaves': 222, 'max_depth': 1, 'learning_rate': 0.07627189514327888, 'subsample': 0.8712966724062597, 'colsample_bytree': 0.6895560962073355, 'min_child_samples': 43, 'reg_alpha': 2.7691933879281462e-05, 'reg_lambda': 0.004101360989987857}. Best is trial 19 with value: -0.5296263135086101.

Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 168.528	valid_0's l2: 28401.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 154.497	valid_0's l2: 23869.4
Early stopping, best iteration is:
[125]	valid_0's rmse: 160.235	valid_0's l2: 25675.1
Early stopping, best iteration is:
[31]	valid_0's rmse: 34.2602	valid_0's l2: 1173.76

[I 2025-11-18 03:51:23,742] Trial 44 finished with value: -0.5525430643238988 and parameters: {'num_leaves': 224, 'max_depth': -1, 'learning_rate': 0.07928427427030355, 'subsample': 0.7609201335037282, 'colsample_bytree': 0.6873489401583254, 'min_child_samples': 100, 'reg_alpha': 4.42367887255316e-05, 'reg_lambda': 0.0037229094892934846}. Best is trial 19 with value: -0.5296263135086101.

Early stopping, best iteration is:
[106]	valid_0's rmse: 157.9	valid_0's l2: 24932.4
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:51:26,548] Trial 49 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[241]	valid_0's rmse: 156.995	valid_0's l2: 24647.4
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[119]	valid_0's rmse: 25.7162	valid_0's l2: 661.324
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:51:28,799] Trial 52 pruned.

Early stopping, best iteration is:
[301]	valid_0's rmse: 156.543	valid_0's l2: 24505.6
Early stopping, best iteration is:
[29]	valid_0's rmse: 34.1665	valid_0's l2: 1167.35
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[29]	valid_0's rmse: 33.4252	valid_0's l2: 1117.24

[I 2025-11-18 03:51:31,373] Trial 51 finished with value: -0.5278915216753832 and parameters: {'num_leaves': 217, 'max_depth': 1, 'learning_rate': 0.07476672026320555, 'subsample': 0.870444840767931, 'colsample_bytree': 0.7975502000679396, 'min_child_samples': 39, 'reg_alpha': 0.02588576237356899, 'reg_lambda': 0.0238685841632671}. Best is trial 51 with value: -0.5278915216753832.
[I 2025-11-18 03:51:31,828] Trial 47 finished with value: -0.5518277408492304 and parameters: {'num_leaves': 226, 'max_depth': -1, 'learning_rate': 0.07783763208187586, 'subsample': 0.7784022804004226, 'colsample_bytree': 0.7148899691438461, 'min_child_samples': 100, 'reg_alpha': 5.847870443827011e-05, 'reg_lambda': 0.004560344183179569}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[260]	valid_0's rmse: 24.0602	valid_0's l2: 578.893
Early stopping, best iteration is:
[137]	valid_0's rmse: 25.8784	valid_0's l2: 669.692
Early stopping, best iteration is:
[176]	valid_0's rmse: 23.9728	valid_0's l2: 574.697
Early stopping, best iteration is:
[46]	valid_0's rmse: 25.5575	valid_0's l2: 653.188
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 roundsTraining until validation scores don't improve for 100 rounds

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[160]	valid_0's rmse: 25.6202	valid_0's l2: 656.393
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 32.4014	valid_0's l2: 1049.85

[I 2025-11-18 03:51:47,098] Trial 53 finished with value: -0.5348525930580376 and parameters: {'num_leaves': 218, 'max_depth': 3, 'learning_rate': 0.08320046451613834, 'subsample': 0.8620166759236434, 'colsample_bytree': 0.7973274292574529, 'min_child_samples': 47, 'reg_alpha': 0.654301937154821, 'reg_lambda': 0.004347945136061621}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[491]	valid_0's rmse: 154.434	valid_0's l2: 23849.8
Early stopping, best iteration is:
[83]	valid_0's rmse: 157.745	valid_0's l2: 24883.4
Early stopping, best iteration is:
[388]	valid_0's rmse: 154.353	valid_0's l2: 23824.8
Early stopping, best iteration is:
[187]	valid_0's rmse: 24.215	valid_0's l2: 586.367
Early stopping, best iteration is:
[253]	valid_0's rmse: 156.745	valid_0's l2: 24569.1
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:51:55,619] Trial 57 finished with value: -0.5312425308527639 and parameters: {'num_leaves': 240, 'max_depth': 1, 'learning_rate': 0.26691764535648826, 'subsample': 0.846678914746735, 'colsample_bytree': 0.6604661118058966, 'min_child_samples': 34, 'reg_alpha': 0.36883003241938056, 'reg_lambda': 0.001423836607933207}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.6515	valid_0's l2: 1200.72

[I 2025-11-18 03:51:56,517] Trial 56 finished with value: -0.5328001752759816 and parameters: {'num_leaves': 239, 'max_depth': 1, 'learning_rate': 0.2928721881074972, 'subsample': 0.8697812193423338, 'colsample_bytree': 0.7903784840588522, 'min_child_samples': 46, 'reg_alpha': 0.002033453970195679, 'reg_lambda': 0.022878612709659938}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.9371	valid_0's l2: 1220.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[32]	valid_0's rmse: 33.1548	valid_0's l2: 1099.24

[I 2025-11-18 03:51:59,083] Trial 59 finished with value: -0.5410983696806805 and parameters: {'num_leaves': 178, 'max_depth': 3, 'learning_rate': 0.2938965875888169, 'subsample': 0.8894116615063064, 'colsample_bytree': 0.7980167246167641, 'min_child_samples': 34, 'reg_alpha': 0.5321252897898296, 'reg_lambda': 0.021827892426644478}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[43]	valid_0's rmse: 33.7219	valid_0's l2: 1137.17

[I 2025-11-18 03:52:03,910] Trial 43 finished with value: -0.5488520716160014 and parameters: {'num_leaves': 228, 'max_depth': -1, 'learning_rate': 0.06580183661962127, 'subsample': 0.7674023590436799, 'colsample_bytree': 0.7131550223956811, 'min_child_samples': 44, 'reg_alpha': 0.4895584170925576, 'reg_lambda': 0.006157453311533988}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[765]	valid_0's rmse: 158.391	valid_0's l2: 25087.6
Early stopping, best iteration is:
[358]	valid_0's rmse: 156.677	valid_0's l2: 24547.7
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[36]	valid_0's rmse: 34.0545	valid_0's l2: 1159.71

[I 2025-11-18 03:52:07,800] Trial 45 finished with value: -0.5558289678829981 and parameters: {'num_leaves': 227, 'max_depth': -1, 'learning_rate': 0.07737944405305136, 'subsample': 0.7680721061844059, 'colsample_bytree': 0.7056541231426674, 'min_child_samples': 32, 'reg_alpha': 5.163039212692437e-05, 'reg_lambda': 0.005635501987712243}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[903]	valid_0's rmse: 24.1938	valid_0's l2: 585.341
Early stopping, best iteration is:
[606]	valid_0's rmse: 156.954	valid_0's l2: 24634.6
Early stopping, best iteration is:
[159]	valid_0's rmse: 32.8514	valid_0's l2: 1079.21

[I 2025-11-18 03:52:13,612] Trial 54 finished with value: -0.5394390542161595 and parameters: {'num_leaves': 216, 'max_depth': 4, 'learning_rate': 0.07149639960721188, 'subsample': 0.8658276712285391, 'colsample_bytree': 0.8032771338196425, 'min_child_samples': 46, 'reg_alpha': 0.0021740742261856676, 'reg_lambda': 0.025748453286386096}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[651]	valid_0's rmse: 153.466	valid_0's l2: 23551.9
Early stopping, best iteration is:
[107]	valid_0's rmse: 32.9609	valid_0's l2: 1086.42
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:52:22,615] Trial 55 finished with value: -0.5408333257194035 and parameters: {'num_leaves': 179, 'max_depth': 4, 'learning_rate': 0.0708316389612477, 'subsample': 0.8433392624831884, 'colsample_bytree': 0.7963661728989462, 'min_child_samples': 34, 'reg_alpha': 1.0692548355519575, 'reg_lambda': 0.0011019489935778528}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:52:26,816] Trial 60 finished with value: -0.5323044215682243 and parameters: {'num_leaves': 242, 'max_depth': 1, 'learning_rate': 0.2879276233822052, 'subsample': 0.8953780738142179, 'colsample_bytree': 0.7972323843653808, 'min_child_samples': 34, 'reg_alpha': 0.0020579138268785177, 'reg_lambda': 0.02697064747182759}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.8966	valid_0's l2: 1217.78
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 168.619	valid_0's l2: 28432.3

[I 2025-11-18 03:52:29,369] Trial 31 pruned.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[995]	valid_0's rmse: 155.488	valid_0's l2: 24176.6
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 24.2189	valid_0's l2: 586.556
Early stopping, best iteration is:
[175]	valid_0's rmse: 32.4051	valid_0's l2: 1050.09

[I 2025-11-18 03:52:32,991] Trial 58 finished with value: -0.5374009620504684 and parameters: {'num_leaves': 186, 'max_depth': 3, 'learning_rate': 0.055001215527138464, 'subsample': 0.8997297054804141, 'colsample_bytree': 0.7931550793654193, 'min_child_samples': 34, 'reg_alpha': 0.0017962917028605991, 'reg_lambda': 0.06609658902027876}. Best is trial 51 with value: -0.5278915216753832.

Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 27.4628	valid_0's l2: 754.203
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 34.8021	valid_0's l2: 1211.18
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 24.3112	valid_0's l2: 591.033
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[90]	valid_0's rmse: 26.2619	valid_0's l2: 689.689
Early stopping, best iteration is:
[295]	valid_0's rmse: 34.3129	valid_0's l2: 1177.38

[I 2025-11-18 03:52:49,652] Trial 61 finished with value: -0.5330305416499526 and parameters: {'num_leaves': 243, 'max_depth': 1, 'learning_rate': 0.05476283925187255, 'subsample': 0.900388480604189, 'colsample_bytree': 0.6320813576165664, 'min_child_samples': 34, 'reg_alpha': 0.5194395164450631, 'reg_lambda': 0.0011700651903160148}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[86]	valid_0's rmse: 26.5776	valid_0's l2: 706.367
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[980]	valid_0's rmse: 155.692	valid_0's l2: 24240

[I 2025-11-18 03:52:57,949] Trial 13 pruned.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:52:59,564] Trial 17 finished with value: -0.5784438850738464 and parameters: {'num_leaves': 217, 'max_depth': 7, 'learning_rate': 0.0014389361780301425, 'subsample': 0.8786349642548815, 'colsample_bytree': 0.8892637030029703, 'min_child_samples': 51, 'reg_alpha': 0.00014860196982260628, 'reg_lambda': 2.486955107614867}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[86]	valid_0's rmse: 26.5736	valid_0's l2: 706.158
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 155.861	valid_0's l2: 24292.6
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[274]	valid_0's rmse: 34.5073	valid_0's l2: 1190.75
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:53:11,391] Trial 66 finished with value: -0.5342616672293828 and parameters: {'num_leaves': 242, 'max_depth': 1, 'learning_rate': 0.04917621063677048, 'subsample': 0.8322126381893928, 'colsample_bytree': 0.6050322172409044, 'min_child_samples': 26, 'reg_alpha': 0.04119068889202216, 'reg_lambda': 0.001010317779108028}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[137]	valid_0's rmse: 26.5611	valid_0's l2: 705.495
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[48]	valid_0's rmse: 34.9522	valid_0's l2: 1221.65

[I 2025-11-18 03:53:14,284] Trial 67 finished with value: -0.5368519596114951 and parameters: {'num_leaves': 243, 'max_depth': 1, 'learning_rate': 0.04550179003905299, 'subsample': 0.9134312737005744, 'colsample_bytree': 0.6588862819930315, 'min_child_samples': 28, 'reg_alpha': 0.04141512404493708, 'reg_lambda': 0.0744470050120209}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[60]	valid_0's rmse: 26.4015	valid_0's l2: 697.042
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[67]	valid_0's rmse: 26.2843	valid_0's l2: 690.866
Early stopping, best iteration is:
[30]	valid_0's rmse: 26.2087	valid_0's l2: 686.896
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[22]	valid_0's rmse: 26.073	valid_0's l2: 679.802
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[27]	valid_0's rmse: 26.2758	valid_0's l2: 690.416
Early stopping, best iteration is:
[151]	valid_0's rmse: 26.5406	valid_0's l2: 704.405
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 166.451	valid_0's l2: 27706
Early stopping, best iteration is:
[119]	valid_0's rmse: 161.386	valid_0's l2: 26045.5
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[147]	valid_0's rmse: 162.229	valid_0's l2: 26318.3
Early stopping, best iteration is:
[105]	valid_0's rmse: 26.4815	valid_0's l2: 701.271
Early stopping, best iteration is:
[74]	valid_0's rmse: 161.319	valid_0's l2: 26023.8

[I 2025-11-18 03:54:16,962] Trial 63 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[73]	valid_0's rmse: 160.211	valid_0's l2: 25667.7

[I 2025-11-18 03:54:24,066] Trial 71 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[124]	valid_0's rmse: 26.2469	valid_0's l2: 688.902

[I 2025-11-18 03:54:28,031] Trial 22 pruned.

Early stopping, best iteration is:
[119]	valid_0's rmse: 162.341	valid_0's l2: 26354.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[55]	valid_0's rmse: 157.723	valid_0's l2: 24876.5
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[26]	valid_0's rmse: 25.9814	valid_0's l2: 675.035
Early stopping, best iteration is:
[46]	valid_0's rmse: 34.397	valid_0's l2: 1183.15
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[19]	valid_0's rmse: 25.9799	valid_0's l2: 674.955

[I 2025-11-18 03:54:57,255] Trial 72 finished with value: -0.5548313972878665 and parameters: {'num_leaves': 199, 'max_depth': 0, 'learning_rate': 0.14501860036524308, 'subsample': 0.9212705864532017, 'colsample_bytree': 0.6585781396060543, 'min_child_samples': 24, 'reg_alpha': 0.018268698561587065, 'reg_lambda': 0.0021829148236642767}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[12]	valid_0's rmse: 26.4718	valid_0's l2: 700.754
Early stopping, best iteration is:
[296]	valid_0's rmse: 161.75	valid_0's l2: 26163.1
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[164]	valid_0's rmse: 158.548	valid_0's l2: 25137.6
Early stopping, best iteration is:
[234]	valid_0's rmse: 161.952	valid_0's l2: 26228.5
Early stopping, best iteration is:
[86]	valid_0's rmse: 34.0521	valid_0's l2: 1159.54

[I 2025-11-18 03:55:10,704] Trial 62 finished with value: -0.5548586769545759 and parameters: {'num_leaves': 245, 'max_depth': 0, 'learning_rate': 0.052431331872332156, 'subsample': 0.8909138789278532, 'colsample_bytree': 0.6513202478897889, 'min_child_samples': 34, 'reg_alpha': 0.42523405378825696, 'reg_lambda': 0.0014033071565190073}. Best is trial 51 with value: -0.5278915216753832.
[I 2025-11-18 03:55:11,159] Trial 68 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:55:14,311] Trial 64 pruned.
[I 2025-11-18 03:55:14,469] Trial 65 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[83]	valid_0's rmse: 25.0904	valid_0's l2: 629.526
Early stopping, best iteration is:
[180]	valid_0's rmse: 24.1416	valid_0's l2: 582.819
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 25.483	valid_0's l2: 649.386
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[106]	valid_0's rmse: 25.1097	valid_0's l2: 630.495
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 153.46	valid_0's l2: 23550.1
Early stopping, best iteration is:
[81]	valid_0's rmse: 153.752	valid_0's l2: 23639.5
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[174]	valid_0's rmse: 155.501	valid_0's l2: 24180.5
Early stopping, best iteration is:
[25]	valid_0's rmse: 161.94	valid_0's l2: 26224.7

[I 2025-11-18 03:55:34,607] Trial 77 pruned.

Early stopping, best iteration is:
[20]	valid_0's rmse: 34.6918	valid_0's l2: 1203.52
Early stopping, best iteration is:
[82]	valid_0's rmse: 33.6849	valid_0's l2: 1134.67

[I 2025-11-18 03:55:34,934] Trial 73 finished with value: -0.5517669132078479 and parameters: {'num_leaves': 245, 'max_depth': 0, 'learning_rate': 0.14477887521339503, 'subsample': 0.923105312492657, 'colsample_bytree': 0.821443578766971, 'min_child_samples': 25, 'reg_alpha': 0.03326269260890384, 'reg_lambda': 0.001739682281314735}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[12]	valid_0's rmse: 25.8288	valid_0's l2: 667.126
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:55:36,569] Trial 69 finished with value: -0.5558417153493127 and parameters: {'num_leaves': 244, 'max_depth': 0, 'learning_rate': 0.0507596652785665, 'subsample': 0.9269140752253378, 'colsample_bytree': 0.6521119605439948, 'min_child_samples': 24, 'reg_alpha': 0.02596502139260387, 'reg_lambda': 0.001598338217137834}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[787]	valid_0's rmse: 153.598	valid_0's l2: 23592.3
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[46]	valid_0's rmse: 156.95	valid_0's l2: 24633.4
Early stopping, best iteration is:
[97]	valid_0's rmse: 24.8232	valid_0's l2: 616.193
Early stopping, best iteration is:
[76]	valid_0's rmse: 25.3877	valid_0's l2: 644.533
Early stopping, best iteration is:
[21]	valid_0's rmse: 157.043	valid_0's l2: 24662.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[252]	valid_0's rmse: 32.7034	valid_0's l2: 1069.51
Early stopping, best iteration is:
[256]	valid_0's rmse: 23.8769	valid_0's l2: 570.106
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[147]	valid_0's rmse: 32.7281	valid_0's l2: 1071.13

[I 2025-11-18 03:55:45,520] Trial 82 finished with value: -0.532795395184796 and parameters: {'num_leaves': 209, 'max_depth': 2, 'learning_rate': 0.2688922439637994, 'subsample': 0.8774583562283484, 'colsample_bytree': 0.757067361823104, 'min_child_samples': 18, 'reg_alpha': 0.18835938517188866, 'reg_lambda': 0.041533693178420344}. Best is trial 51 with value: -0.5278915216753832.
[I 2025-11-18 03:55:45,523] Trial 80 finished with value: -0.5296429267997397 and parameters: {'num_leaves': 236, 'max_depth': 2, 'learning_rate': 0.2477240922411495, 'subsample': 0.798042236452938, 'colsample_bytree': 0.8255901996199855, 'min_child_samples': 58, 'reg_alpha': 0.0031466629258944958, 'reg_lambda': 0.03453276638758413}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:55:46,926] Trial 81 finished with value: -0.5314096112586338 and parameters: {'num_leaves': 211, 'max_depth': 1, 'learning_rate': 0.2656908414405527, 'subsample': 0.7976589672484475, 'colsample_bytree': 0.7580325183618795, 'min_child_samples': 39, 'reg_alpha': 6.60379473752318, 'reg_lambda': 0.16087796502646573}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.7385	valid_0's l2: 1206.76
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[124]	valid_0's rmse: 154.578	valid_0's l2: 23894.5
Early stopping, best iteration is:
[118]	valid_0's rmse: 154.711	valid_0's l2: 23935.5
Early stopping, best iteration is:
[70]	valid_0's rmse: 25.3975	valid_0's l2: 645.032
Early stopping, best iteration is:
[300]	valid_0's rmse: 33.1722	valid_0's l2: 1100.39
Early stopping, best iteration is:
[87]	valid_0's rmse: 25.0409	valid_0's l2: 627.045

[I 2025-11-18 03:55:52,863] Trial 83 finished with value: -0.5347288712973204 and parameters: {'num_leaves': 209, 'max_depth': 2, 'learning_rate': 0.234389400214255, 'subsample': 0.7944897617305569, 'colsample_bytree': 0.8198997810790073, 'min_child_samples': 38, 'reg_alpha': 0.0032218690699486385, 'reg_lambda': 0.03729681593928093}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[117]	valid_0's rmse: 25.3063	valid_0's l2: 640.407
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[286]	valid_0's rmse: 162.028	valid_0's l2: 26253.2
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[212]	valid_0's rmse: 158.485	valid_0's l2: 25117.4
Early stopping, best iteration is:
[108]	valid_0's rmse: 155.114	valid_0's l2: 24060.5
Early stopping, best iteration is:
[220]	valid_0's rmse: 153.791	valid_0's l2: 23651.7
Early stopping, best iteration is:
[148]	valid_0's rmse: 154.747	valid_0's l2: 23946.6
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[703]	valid_0's rmse: 153.713	valid_0's l2: 23627.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[841]	valid_0's rmse: 24.0331	valid_0's l2: 577.589
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[313]	valid_0's rmse: 32.9749	valid_0's l2: 1087.35

[I 2025-11-18 03:56:09,902] Trial 85 finished with value: -0.5345950979341977 and parameters: {'num_leaves': 214, 'max_depth': 2, 'learning_rate': 0.23817166420397573, 'subsample': 0.8761885810874015, 'colsample_bytree': 0.7595936829483074, 'min_child_samples': 37, 'reg_alpha': 0.21140045947977268, 'reg_lambda': 0.8717802802578632}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[418]	valid_0's rmse: 33.0581	valid_0's l2: 1092.84
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:56:13,210] Trial 87 finished with value: -0.5381587906026329 and parameters: {'num_leaves': 212, 'max_depth': 2, 'learning_rate': 0.24586451232963108, 'subsample': 0.8219643629036315, 'colsample_bytree': 0.7550021026299751, 'min_child_samples': 57, 'reg_alpha': 0.2193885516188456, 'reg_lambda': 0.03140025817609316}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[14]	valid_0's rmse: 34.0239	valid_0's l2: 1157.63

[I 2025-11-18 03:56:13,854] Trial 86 finished with value: -0.5293911227185333 and parameters: {'num_leaves': 210, 'max_depth': 1, 'learning_rate': 0.24786663894439037, 'subsample': 0.8726402871839598, 'colsample_bytree': 0.8400413879620261, 'min_child_samples': 38, 'reg_alpha': 0.19841656376898134, 'reg_lambda': 0.15505244499200116}. Best is trial 51 with value: -0.5278915216753832.
[I 2025-11-18 03:56:13,908] Trial 84 finished with value: -0.5309629416900578 and parameters: {'num_leaves': 211, 'max_depth': 2, 'learning_rate': 0.23336638167357768, 'subsample': 0.8489943018352014, 'colsample_bytree': 0.7564825042080667, 'min_child_samples': 38, 'reg_alpha': 4.2078882249354315e-06, 'reg_lambda': 0.13644179243115173}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.6252	valid_0's l2: 1198.9
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 34.206	valid_0's l2: 1170.05
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[225]	valid_0's rmse: 32.9385	valid_0's l2: 1084.94

[I 2025-11-18 03:56:16,899] Trial 89 finished with value: -0.532773838523729 and parameters: {'num_leaves': 208, 'max_depth': 2, 'learning_rate': 0.23164540832441918, 'subsample': 0.7929926786728441, 'colsample_bytree': 0.8375783202269641, 'min_child_samples': 58, 'reg_alpha': 8.090691140241058, 'reg_lambda': 0.14928527373848785}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[22]	valid_0's rmse: 157.028	valid_0's l2: 24657.7

[I 2025-11-18 03:56:18,133] Trial 79 pruned.
[I 2025-11-18 03:56:18,551] Trial 78 finished with value: -0.5527343928556862 and parameters: {'num_leaves': 203, 'max_depth': 0, 'learning_rate': 0.24172777033692555, 'subsample': 0.7979018416096524, 'colsample_bytree': 0.8196284781875789, 'min_child_samples': 38, 'reg_alpha': 0.0032372011487996387, 'reg_lambda': 0.038702529431140345}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.8769	valid_0's l2: 1216.4
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[120]	valid_0's rmse: 25.5856	valid_0's l2: 654.624
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 161.45	valid_0's l2: 26066.1
Early stopping, best iteration is:
[107]	valid_0's rmse: 25.5174	valid_0's l2: 651.138
Early stopping, best iteration is:
[95]	valid_0's rmse: 25.6725	valid_0's l2: 659.08
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[110]	valid_0's rmse: 25.6031	valid_0's l2: 655.519
Early stopping, best iteration is:
[23]	valid_0's rmse: 34.0579	valid_0's l2: 1159.94
Early stopping, best iteration is:
[359]	valid_0's rmse: 32.8074	valid_0's l2: 1076.33

[I 2025-11-18 03:56:23,039] Trial 76 finished with value: -0.5461731282086603 and parameters: {'num_leaves': 197, 'max_depth': 0, 'learning_rate': 0.14536728564237397, 'subsample': 0.8010240036309441, 'colsample_bytree': 0.8213100151098989, 'min_child_samples': 38, 'reg_alpha': 0.0005260130696848007, 'reg_lambda': 0.03225804963123277}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:56:24,288] Trial 88 finished with value: -0.5325940127566103 and parameters: {'num_leaves': 209, 'max_depth': 2, 'learning_rate': 0.24164761564645681, 'subsample': 0.6035974481876993, 'colsample_bytree': 0.7572931735674133, 'min_child_samples': 57, 'reg_alpha': 0.26990935991682713, 'reg_lambda': 0.03428305905437559}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[107]	valid_0's rmse: 25.5029	valid_0's l2: 650.4
Early stopping, best iteration is:
[127]	valid_0's rmse: 25.2653	valid_0's l2: 638.334
Early stopping, best iteration is:
[126]	valid_0's rmse: 25.5325	valid_0's l2: 651.907
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[71]	valid_0's rmse: 25.3246	valid_0's l2: 641.337
Early stopping, best iteration is:
[274]	valid_0's rmse: 160.348	valid_0's l2: 25711.4
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[460]	valid_0's rmse: 24.0323	valid_0's l2: 577.55
Early stopping, best iteration is:
[191]	valid_0's rmse: 156.862	valid_0's l2: 24605.8
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:56:36,780] Trial 75 pruned.

Early stopping, best iteration is:
[256]	valid_0's rmse: 156.995	valid_0's l2: 24647.3
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[259]	valid_0's rmse: 157.061	valid_0's l2: 24668.1
Early stopping, best iteration is:
[269]	valid_0's rmse: 157.45	valid_0's l2: 24790.4
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:56:40,935] Trial 94 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[126]	valid_0's rmse: 157.847	valid_0's l2: 24915.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[269]	valid_0's rmse: 157	valid_0's l2: 24649.1
Did not meet early stopping. Best iteration is:
[996]	valid_0's rmse: 154.66	valid_0's l2: 23919.6
Early stopping, best iteration is:
[311]	valid_0's rmse: 157.906	valid_0's l2: 24934.4
Early stopping, best iteration is:
[264]	valid_0's rmse: 156.657	valid_0's l2: 24541.4
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 25.678	valid_0's l2: 659.362
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[282]	valid_0's rmse: 25.5484	valid_0's l2: 652.719
Early stopping, best iteration is:
[134]	valid_0's rmse: 32.5962	valid_0's l2: 1062.51

[I 2025-11-18 03:56:51,584] Trial 92 finished with value: -0.5373143799431928 and parameters: {'num_leaves': 235, 'max_depth': 3, 'learning_rate': 0.10047354187691508, 'subsample': 0.8486630854207852, 'colsample_bytree': 0.8343754132327573, 'min_child_samples': 50, 'reg_alpha': 1.567257094762895, 'reg_lambda': 0.14347978105407375}. Best is trial 51 with value: -0.5278915216753832.
[I 2025-11-18 03:56:52,190] Trial 15 finished with value: -0.5696390066606334 and parameters: {'num_leaves': 152, 'max_depth': -1, 'learning_rate': 0.0019213552153170435, 'subsample': 0.7091560358026516, 'colsample_bytree': 0.8205582622073023, 'min_child_samples': 90, 'reg_alpha': 1.4261477924661883e-07, 'reg_lambda': 0.02188276564585203}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[125]	valid_0's rmse: 32.3795	valid_0's l2: 1048.43

[I 2025-11-18 03:56:53,575] Trial 91 finished with value: -0.5371354424262316 and parameters: {'num_leaves': 237, 'max_depth': 3, 'learning_rate': 0.101446593916281, 'subsample': 0.8524107329914865, 'colsample_bytree': 0.8460320493965475, 'min_child_samples': 60, 'reg_alpha': 7.567432995558796, 'reg_lambda': 0.18326134146076734}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 roundsTraining until validation scores don't improve for 100 rounds

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:56:54,929] Trial 25 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[94]	valid_0's rmse: 32.6447	valid_0's l2: 1065.67

[I 2025-11-18 03:56:55,552] Trial 98 finished with value: -0.5377413248857799 and parameters: {'num_leaves': 188, 'max_depth': 3, 'learning_rate': 0.17101570511455166, 'subsample': 0.8530795765835909, 'colsample_bytree': 0.8425888399513084, 'min_child_samples': 50, 'reg_alpha': 6.00787863427863e-06, 'reg_lambda': 0.15025829204429567}. Best is trial 51 with value: -0.5278915216753832.

Early stopping, best iteration is:
[177]	valid_0's rmse: 32.6077	valid_0's l2: 1063.26

[I 2025-11-18 03:56:56,416] Trial 93 finished with value: -0.5386954428837102 and parameters: {'num_leaves': 129, 'max_depth': 3, 'learning_rate': 0.09502282298692596, 'subsample': 0.8468390024172054, 'colsample_bytree': 0.8454241774820519, 'min_child_samples': 41, 'reg_alpha': 7.531339576783246, 'reg_lambda': 0.14892797994717116}. Best is trial 51 with value: -0.5278915216753832.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[119]	valid_0's rmse: 33.5571	valid_0's l2: 1126.08

[I 2025-11-18 03:56:57,435] Trial 90 finished with value: -0.5277676137488985 and parameters: {'num_leaves': 212, 'max_depth': 1, 'learning_rate': 0.09825970546112957, 'subsample': 0.6037607008778383, 'colsample_bytree': 0.6792825428650643, 'min_child_samples': 39, 'reg_alpha': 7.800852455705677, 'reg_lambda': 0.13386060009659118}. Best is trial 90 with value: -0.5277676137488985.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[119]	valid_0's rmse: 156.632	valid_0's l2: 24533.4

[I 2025-11-18 03:56:59,871] Trial 101 pruned.

Early stopping, best iteration is:
[199]	valid_0's rmse: 32.5624	valid_0's l2: 1060.31

[I 2025-11-18 03:57:01,052] Trial 95 finished with value: -0.5371204650284921 and parameters: {'num_leaves': 132, 'max_depth': 3, 'learning_rate': 0.09523761822898509, 'subsample': 0.8497086784556468, 'colsample_bytree': 0.6857893891540545, 'min_child_samples': 41, 'reg_alpha': 2.2624032446731834, 'reg_lambda': 0.15322275462012172}. Best is trial 90 with value: -0.5277676137488985.

Early stopping, best iteration is:
[225]	valid_0's rmse: 32.3817	valid_0's l2: 1048.57
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:57:01,426] Trial 96 finished with value: -0.5366034925594977 and parameters: {'num_leaves': 201, 'max_depth': 3, 'learning_rate': 0.0920558503130296, 'subsample': 0.8466828211818764, 'colsample_bytree': 0.8418898149592315, 'min_child_samples': 42, 'reg_alpha': 3.9109681246999797, 'reg_lambda': 0.1525368629882077}. Best is trial 90 with value: -0.5277676137488985.

Early stopping, best iteration is:
[175]	valid_0's rmse: 32.8402	valid_0's l2: 1078.48

[I 2025-11-18 03:57:01,909] Trial 97 finished with value: -0.5380390874960681 and parameters: {'num_leaves': 195, 'max_depth': 3, 'learning_rate': 0.10062329585711498, 'subsample': 0.8513431837909231, 'colsample_bytree': 0.782657292393315, 'min_child_samples': 42, 'reg_alpha': 5.341234887954253e-06, 'reg_lambda': 0.21101826173846247}. Best is trial 90 with value: -0.5277676137488985.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[223]	valid_0's rmse: 24.0447	valid_0's l2: 578.149
Early stopping, best iteration is:
[526]	valid_0's rmse: 23.9741	valid_0's l2: 574.759
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[537]	valid_0's rmse: 23.9985	valid_0's l2: 575.926
Did not meet early stopping. Best iteration is:
[953]	valid_0's rmse: 154.16	valid_0's l2: 23765.3
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[634]	valid_0's rmse: 24.0928	valid_0's l2: 580.461
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 24.6823	valid_0's l2: 609.217
Early stopping, best iteration is:
[157]	valid_0's rmse: 33.6818	valid_0's l2: 1134.46
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[560]	valid_0's rmse: 24.0677	valid_0's l2: 579.253
Early stopping, best iteration is:
[672]	valid_0's rmse: 24.0631	valid_0's l2: 579.031
Early stopping, best iteration is:
[510]	valid_0's rmse: 24.103	valid_0's l2: 580.957

[I 2025-11-18 03:57:15,452] Trial 70 finished with value: -0.5562710672685661 and parameters: {'num_leaves': 245, 'max_depth': 0, 'learning_rate': 0.030159112995460376, 'subsample': 0.9181549744225308, 'colsample_bytree': 0.6609018036386992, 'min_child_samples': 27, 'reg_alpha': 0.020145846257481163, 'reg_lambda': 0.0024578311474046607}. Best is trial 90 with value: -0.5277676137488985.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[163]	valid_0's rmse: 33.3905	valid_0's l2: 1114.93
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:57:16,552] Trial 99 finished with value: -0.5285868191104205 and parameters: {'num_leaves': 190, 'max_depth': 1, 'learning_rate': 0.17237634468181284, 'subsample': 0.8506973445154429, 'colsample_bytree': 0.6759714496018604, 'min_child_samples': 42, 'reg_alpha': 4.050288958120939e-06, 'reg_lambda': 0.06008494160580996}. Best is trial 90 with value: -0.5277676137488985.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[60]	valid_0's rmse: 33.9706	valid_0's l2: 1154
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[946]	valid_0's rmse: 24.0195	valid_0's l2: 576.935

[I 2025-11-18 03:57:17,661] Trial 74 finished with value: -0.5492862906994643 and parameters: {'num_leaves': 199, 'max_depth': 0, 'learning_rate': 0.03265668490852283, 'subsample': 0.9232787903193975, 'colsample_bytree': 0.8231776060467035, 'min_child_samples': 28, 'reg_alpha': 6.1672542805027e-06, 'reg_lambda': 0.0018743330274919253}. Best is trial 90 with value: -0.5277676137488985.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 24.5124	valid_0's l2: 600.859
Early stopping, best iteration is:
[688]	valid_0's rmse: 154.238	valid_0's l2: 23789.2
Did not meet early stopping. Best iteration is:
[995]	valid_0's rmse: 24.1873	valid_0's l2: 585.026
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[747]	valid_0's rmse: 157.043	valid_0's l2: 24662.4
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:57:28,493] Trial 107 finished with value: -0.5324963450400572 and parameters: {'num_leaves': 223, 'max_depth': 1, 'learning_rate': 0.2967382101318256, 'subsample': 0.8876149102109286, 'colsample_bytree': 0.6743442013890986, 'min_child_samples': 30, 'reg_alpha': 3.402084516872539, 'reg_lambda': 0.017051771032700093}. Best is trial 90 with value: -0.5277676137488985.

Early stopping, best iteration is:
[7]	valid_0's rmse: 34.931	valid_0's l2: 1220.18
Early stopping, best iteration is:
[485]	valid_0's rmse: 24.1465	valid_0's l2: 583.052
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[917]	valid_0's rmse: 154.188	valid_0's l2: 23773.8
Early stopping, best iteration is:
[540]	valid_0's rmse: 24.163	valid_0's l2: 583.853
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[957]	valid_0's rmse: 153.704	valid_0's l2: 23624.9
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 156.612	valid_0's l2: 24527.4
Did not meet early stopping. Best iteration is:
[953]	valid_0's rmse: 24.2567	valid_0's l2: 588.388

[I 2025-11-18 03:57:37,742] Trial 104 finished with value: -0.5282536280935227 and parameters: {'num_leaves': 186, 'max_depth': 1, 'learning_rate': 0.17207282995042844, 'subsample': 0.7243267530108032, 'colsample_bytree': 0.6727680537253812, 'min_child_samples': 42, 'reg_alpha': 5.843533449610138e-06, 'reg_lambda': 3.5063301936845592}. Best is trial 90 with value: -0.5277676137488985.

Early stopping, best iteration is:
[11]	valid_0's rmse: 33.9314	valid_0's l2: 1151.34
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[975]	valid_0's rmse: 154.428	valid_0's l2: 23848.1
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 154.4	valid_0's l2: 23839.5
Early stopping, best iteration is:
[452]	valid_0's rmse: 24.1315	valid_0's l2: 582.329

[I 2025-11-18 03:57:42,651] Trial 103 finished with value: -0.5272176102991865 and parameters: {'num_leaves': 185, 'max_depth': 1, 'learning_rate': 0.17312918974288102, 'subsample': 0.8190398127833705, 'colsample_bytree': 0.7708892592851043, 'min_child_samples': 41, 'reg_alpha': 1.692664008933837e-05, 'reg_lambda': 0.20493939142519246}. Best is trial 103 with value: -0.5272176102991865.

Early stopping, best iteration is:
[57]	valid_0's rmse: 33.8981	valid_0's l2: 1149.08
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:57:44,679] Trial 102 finished with value: -0.5386149686789246 and parameters: {'num_leaves': 189, 'max_depth': 1, 'learning_rate': 0.03640881280524339, 'subsample': 0.7292655951663249, 'colsample_bytree': 0.6727312087381015, 'min_child_samples': 42, 'reg_alpha': 3.535320194144217, 'reg_lambda': 0.0554396337474463}. Best is trial 103 with value: -0.5272176102991865.

Early stopping, best iteration is:
[52]	valid_0's rmse: 34.4698	valid_0's l2: 1188.17
Early stopping, best iteration is:
[260]	valid_0's rmse: 24.2722	valid_0's l2: 589.139
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[956]	valid_0's rmse: 154.385	valid_0's l2: 23834.8
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[992]	valid_0's rmse: 153.905	valid_0's l2: 23686.6
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 155.259	valid_0's l2: 24105.4
Early stopping, best iteration is:
[94]	valid_0's rmse: 33.4193	valid_0's l2: 1116.85

[I 2025-11-18 03:57:49,215] Trial 109 finished with value: -0.5271079357173947 and parameters: {'num_leaves': 223, 'max_depth': 1, 'learning_rate': 0.12468471736668335, 'subsample': 0.6602418864721029, 'colsample_bytree': 0.6729356332995603, 'min_child_samples': 30, 'reg_alpha': 2.1894054966066405, 'reg_lambda': 0.2422695066119941}. Best is trial 109 with value: -0.5271079357173947.

Early stopping, best iteration is:
[97]	valid_0's rmse: 34.45	valid_0's l2: 1186.8

[I 2025-11-18 03:57:50,467] Trial 112 finished with value: -0.531278356081788 and parameters: {'num_leaves': 222, 'max_depth': 1, 'learning_rate': 0.1254498167819395, 'subsample': 0.7313558940563049, 'colsample_bytree': 0.6695354092095945, 'min_child_samples': 30, 'reg_alpha': 1.4922472179261997e-05, 'reg_lambda': 0.05384784266826573}. Best is trial 109 with value: -0.5271079357173947.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[975]	valid_0's rmse: 154.489	valid_0's l2: 23867
Did not meet early stopping. Best iteration is:
[948]	valid_0's rmse: 154.166	valid_0's l2: 23767.1

[I 2025-11-18 03:57:56,353] Trial 106 finished with value: -0.5284798803655978 and parameters: {'num_leaves': 224, 'max_depth': 1, 'learning_rate': 0.1263895772958917, 'subsample': 0.8180425186506413, 'colsample_bytree': 0.6728626689527416, 'min_child_samples': 42, 'reg_alpha': 3.1535776450240856, 'reg_lambda': 0.014867917014947144}. Best is trial 109 with value: -0.5271079357173947.

Early stopping, best iteration is:
[101]	valid_0's rmse: 33.7488	valid_0's l2: 1138.98
Early stopping, best iteration is:
[394]	valid_0's rmse: 32.4004	valid_0's l2: 1049.78
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:57:57,359] Trial 100 finished with value: -0.5370424129800531 and parameters: {'num_leaves': 132, 'max_depth': 3, 'learning_rate': 0.03712471239790902, 'subsample': 0.8460769407295962, 'colsample_bytree': 0.8427912829615826, 'min_child_samples': 50, 'reg_alpha': 4.864207547474542e-06, 'reg_lambda': 0.01441680597915572}. Best is trial 109 with value: -0.5271079357173947.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[101]	valid_0's rmse: 33.4927	valid_0's l2: 1121.76
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 156.486	valid_0's l2: 24487.9

[I 2025-11-18 03:57:58,049] Trial 108 finished with value: -0.5265527201068086 and parameters: {'num_leaves': 221, 'max_depth': 1, 'learning_rate': 0.1233672346267383, 'subsample': 0.6798523320131443, 'colsample_bytree': 0.7827145264544068, 'min_child_samples': 43, 'reg_alpha': 4.226075739469958, 'reg_lambda': 0.016260595416812774}. Best is trial 108 with value: -0.5265527201068086.

Did not meet early stopping. Best iteration is:
[990]	valid_0's rmse: 153.987	valid_0's l2: 23712
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[560]	valid_0's rmse: 23.9928	valid_0's l2: 575.653
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[189]	valid_0's rmse: 33.8715	valid_0's l2: 1147.28

[I 2025-11-18 03:57:59,843] Trial 111 finished with value: -0.5309299513135556 and parameters: {'num_leaves': 223, 'max_depth': 1, 'learning_rate': 0.06288896816001055, 'subsample': 0.7307334460595676, 'colsample_bytree': 0.6739609918463559, 'min_child_samples': 30, 'reg_alpha': 1.856653061990745e-05, 'reg_lambda': 0.060459764819850007}. Best is trial 108 with value: -0.5265527201068086.

Early stopping, best iteration is:
[860]	valid_0's rmse: 23.8744	valid_0's l2: 569.985
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[100]	valid_0's rmse: 33.4106	valid_0's l2: 1116.27

[I 2025-11-18 03:58:03,521] Trial 105 finished with value: -0.5263494586619047 and parameters: {'num_leaves': 222, 'max_depth': 1, 'learning_rate': 0.1197209514872923, 'subsample': 0.9637514595815206, 'colsample_bytree': 0.8749253801569818, 'min_child_samples': 41, 'reg_alpha': 2.0486342674124326e-05, 'reg_lambda': 0.01701557382423335}. Best is trial 105 with value: -0.5263494586619047.

Early stopping, best iteration is:
[91]	valid_0's rmse: 33.3396	valid_0's l2: 1111.53
Early stopping, best iteration is:
[613]	valid_0's rmse: 23.9927	valid_0's l2: 575.651

[I 2025-11-18 03:58:03,887] Trial 115 finished with value: -0.5274177701360722 and parameters: {'num_leaves': 251, 'max_depth': 1, 'learning_rate': 0.11993956572851558, 'subsample': 0.6516200539201278, 'colsample_bytree': 0.6755470500115259, 'min_child_samples': 30, 'reg_alpha': 1.992954460588207e-05, 'reg_lambda': 0.05830961512818699}. Best is trial 105 with value: -0.5263494586619047.

Did not meet early stopping. Best iteration is:
[997]	valid_0's rmse: 154.923	valid_0's l2: 24001.2
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[979]	valid_0's rmse: 153.671	valid_0's l2: 23614.8

[I 2025-11-18 03:58:07,999] Trial 110 finished with value: -0.5370568646468559 and parameters: {'num_leaves': 223, 'max_depth': 1, 'learning_rate': 0.037724650000512186, 'subsample': 0.7248482832106002, 'colsample_bytree': 0.6733264304621915, 'min_child_samples': 30, 'reg_alpha': 3.9395402976562393, 'reg_lambda': 0.061005097385975454}. Best is trial 105 with value: -0.5263494586619047.

Early stopping, best iteration is:
[53]	valid_0's rmse: 34.409	valid_0's l2: 1183.98
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[82]	valid_0's rmse: 33.5	valid_0's l2: 1122.25

[I 2025-11-18 03:58:09,406] Trial 114 finished with value: -0.5273717621140644 and parameters: {'num_leaves': 167, 'max_depth': 1, 'learning_rate': 0.12453425831944809, 'subsample': 0.9667310194064462, 'colsample_bytree': 0.8777965007062696, 'min_child_samples': 30, 'reg_alpha': 1.7224343291320697e-05, 'reg_lambda': 0.05392697198994226}. Best is trial 105 with value: -0.5263494586619047.

Did not meet early stopping. Best iteration is:
[957]	valid_0's rmse: 153.351	valid_0's l2: 23516.5
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[870]	valid_0's rmse: 23.8799	valid_0's l2: 570.247

[I 2025-11-18 03:58:11,885] Trial 113 finished with value: -0.5292344121343066 and parameters: {'num_leaves': 252, 'max_depth': 1, 'learning_rate': 0.06305294793240727, 'subsample': 0.7189990688036311, 'colsample_bytree': 0.8097032814689272, 'min_child_samples': 31, 'reg_alpha': 0.009215583739926765, 'reg_lambda': 0.055187319078933365}. Best is trial 105 with value: -0.5263494586619047.

Early stopping, best iteration is:
[43]	valid_0's rmse: 33.4471	valid_0's l2: 1118.71
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[733]	valid_0's rmse: 23.8399	valid_0's l2: 568.342
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:58:13,886] Trial 117 finished with value: -0.5326007467319366 and parameters: {'num_leaves': 191, 'max_depth': 1, 'learning_rate': 0.20779429891437462, 'subsample': 0.6485436713401753, 'colsample_bytree': 0.6682868105147209, 'min_child_samples': 36, 'reg_alpha': 1.70574674061154e-05, 'reg_lambda': 3.7081659006482486}. Best is trial 105 with value: -0.5263494586619047.

Early stopping, best iteration is:
[53]	valid_0's rmse: 34.7932	valid_0's l2: 1210.57
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[633]	valid_0's rmse: 24.0872	valid_0's l2: 580.195
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:58:15,913] Trial 116 finished with value: -0.5300764165611307 and parameters: {'num_leaves': 250, 'max_depth': 1, 'learning_rate': 0.20687882296514706, 'subsample': 0.7207303038364465, 'colsample_bytree': 0.8792718759143934, 'min_child_samples': 48, 'reg_alpha': 1.7445015552272394e-05, 'reg_lambda': 0.28136836881895283}. Best is trial 105 with value: -0.5263494586619047.

Early stopping, best iteration is:
[42]	valid_0's rmse: 34.5092	valid_0's l2: 1190.89
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[926]	valid_0's rmse: 23.9124	valid_0's l2: 571.805
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[569]	valid_0's rmse: 24.0185	valid_0's l2: 576.89
Early stopping, best iteration is:
[429]	valid_0's rmse: 24.1943	valid_0's l2: 585.363
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 23.9742	valid_0's l2: 574.761
Early stopping, best iteration is:
[155]	valid_0's rmse: 25.3974	valid_0's l2: 645.027
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[641]	valid_0's rmse: 23.9287	valid_0's l2: 572.585
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 154.505	valid_0's l2: 23871.9
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 154.011	valid_0's l2: 23719.3
Early stopping, best iteration is:
[878]	valid_0's rmse: 23.8673	valid_0's l2: 569.648
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 172.405	valid_0's l2: 29723.6
Early stopping, best iteration is:
[25]	valid_0's rmse: 26.2556	valid_0's l2: 689.355
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[661]	valid_0's rmse: 24.0321	valid_0's l2: 577.541
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[103]	valid_0's rmse: 34.2802	valid_0's l2: 1175.13

[I 2025-11-18 03:58:35,100] Trial 118 finished with value: -0.5292658648067264 and parameters: {'num_leaves': 162, 'max_depth': 1, 'learning_rate': 0.12953361732698224, 'subsample': 0.6784096873180917, 'colsample_bytree': 0.6698747158150696, 'min_child_samples': 49, 'reg_alpha': 1.384042694325129e-05, 'reg_lambda': 3.831486925840322}. Best is trial 105 with value: -0.5263494586619047.

Early stopping, best iteration is:
[201]	valid_0's rmse: 154.949	valid_0's l2: 24009.3
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[993]	valid_0's rmse: 154.423	valid_0's l2: 23846.4
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:58:38,820] Trial 119 finished with value: -0.5262221013084162 and parameters: {'num_leaves': 165, 'max_depth': 1, 'learning_rate': 0.12408402635062929, 'subsample': 0.6962385226057038, 'colsample_bytree': 0.809682711641055, 'min_child_samples': 36, 'reg_alpha': 1.8240006889829224e-05, 'reg_lambda': 4.1757324791286345}. Best is trial 119 with value: -0.5262221013084162.

Early stopping, best iteration is:
[114]	valid_0's rmse: 33.4855	valid_0's l2: 1121.28
Did not meet early stopping. Best iteration is:
[974]	valid_0's rmse: 154.365	valid_0's l2: 23828.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 153.986	valid_0's l2: 23711.6
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 153.933	valid_0's l2: 23695.4
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[52]	valid_0's rmse: 156.66	valid_0's l2: 24542.5
Did not meet early stopping. Best iteration is:
[995]	valid_0's rmse: 154.319	valid_0's l2: 23814.3

[I 2025-11-18 03:58:43,793] Trial 132 pruned.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:58:44,787] Trial 131 finished with value: -0.5364907295022413 and parameters: {'num_leaves': 161, 'max_depth': 2, 'learning_rate': 0.12630332769805425, 'subsample': 0.6597495394768883, 'colsample_bytree': 0.9128172123329272, 'min_child_samples': 48, 'reg_alpha': 1.7243854434359547e-06, 'reg_lambda': 0.08576417054272518}. Best is trial 119 with value: -0.5262221013084162.

Early stopping, best iteration is:
[65]	valid_0's rmse: 33.354	valid_0's l2: 1112.49
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[954]	valid_0's rmse: 154.473	valid_0's l2: 23861.8
Early stopping, best iteration is:
[47]	valid_0's rmse: 26.0859	valid_0's l2: 680.475
Early stopping, best iteration is:
[91]	valid_0's rmse: 33.3471	valid_0's l2: 1112.03

[I 2025-11-18 03:58:47,414] Trial 122 finished with value: -0.5253084186148224 and parameters: {'num_leaves': 167, 'max_depth': 1, 'learning_rate': 0.12154082438148688, 'subsample': 0.6736433469242835, 'colsample_bytree': 0.6939725352999876, 'min_child_samples': 48, 'reg_alpha': 2.0063928557025098e-05, 'reg_lambda': 5.060222206147814}. Best is trial 122 with value: -0.5253084186148224.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[107]	valid_0's rmse: 33.7142	valid_0's l2: 1136.64

[I 2025-11-18 03:58:49,601] Trial 120 finished with value: -0.5276512575694294 and parameters: {'num_leaves': 179, 'max_depth': 1, 'learning_rate': 0.1283192755371879, 'subsample': 0.6696714433663818, 'colsample_bytree': 0.6913096260012096, 'min_child_samples': 48, 'reg_alpha': 1.674043872267522e-05, 'reg_lambda': 3.882121241140513}. Best is trial 122 with value: -0.5253084186148224.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[955]	valid_0's rmse: 154.066	valid_0's l2: 23736.3
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[968]	valid_0's rmse: 153.956	valid_0's l2: 23702.4
Early stopping, best iteration is:
[90]	valid_0's rmse: 33.7384	valid_0's l2: 1138.28

[I 2025-11-18 03:58:52,393] Trial 124 finished with value: -0.5277057666231543 and parameters: {'num_leaves': 167, 'max_depth': 1, 'learning_rate': 0.1315663847132432, 'subsample': 0.6733060318646806, 'colsample_bytree': 0.8110688556928682, 'min_child_samples': 36, 'reg_alpha': 1.0345226369283809, 'reg_lambda': 2.8677492465734673}. Best is trial 122 with value: -0.5253084186148224.

Early stopping, best iteration is:
[29]	valid_0's rmse: 26.3501	valid_0's l2: 694.33
Early stopping, best iteration is:
[180]	valid_0's rmse: 25.4113	valid_0's l2: 645.736
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 153.986	valid_0's l2: 23711.6
Early stopping, best iteration is:
[106]	valid_0's rmse: 33.4883	valid_0's l2: 1121.46

[I 2025-11-18 03:58:54,205] Trial 121 finished with value: -0.5254440072188317 and parameters: {'num_leaves': 181, 'max_depth': 1, 'learning_rate': 0.12440720591785522, 'subsample': 0.6774965981746973, 'colsample_bytree': 0.8108867824299759, 'min_child_samples': 48, 'reg_alpha': 3.007491169186322e-06, 'reg_lambda': 4.144507055459301}. Best is trial 122 with value: -0.5253084186148224.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[167]	valid_0's rmse: 25.5028	valid_0's l2: 650.392
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[168]	valid_0's rmse: 25.5237	valid_0's l2: 651.461
Early stopping, best iteration is:
[150]	valid_0's rmse: 25.3802	valid_0's l2: 644.154
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[99]	valid_0's rmse: 33.5721	valid_0's l2: 1127.08

[I 2025-11-18 03:58:56,546] Trial 123 finished with value: -0.5264981002261598 and parameters: {'num_leaves': 167, 'max_depth': 1, 'learning_rate': 0.11738372844270177, 'subsample': 0.6630552153302147, 'colsample_bytree': 0.6902662780089682, 'min_child_samples': 44, 'reg_alpha': 1.4619393233367738e-05, 'reg_lambda': 3.4646623405804418}. Best is trial 122 with value: -0.5253084186148224.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[87]	valid_0's rmse: 33.3943	valid_0's l2: 1115.18

[I 2025-11-18 03:58:57,277] Trial 125 finished with value: -0.5264591773928129 and parameters: {'num_leaves': 168, 'max_depth': 1, 'learning_rate': 0.12791356043344515, 'subsample': 0.6856904781797573, 'colsample_bytree': 0.6964899383706212, 'min_child_samples': 44, 'reg_alpha': 0.008661108728267317, 'reg_lambda': 4.687398383820677}. Best is trial 122 with value: -0.5253084186148224.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[996]	valid_0's rmse: 154.038	valid_0's l2: 23727.6
Early stopping, best iteration is:
[168]	valid_0's rmse: 25.2684	valid_0's l2: 638.492
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 153.948	valid_0's l2: 23699.9
Early stopping, best iteration is:
[95]	valid_0's rmse: 33.3849	valid_0's l2: 1114.55

[I 2025-11-18 03:59:01,443] Trial 129 finished with value: -0.5270873375972437 and parameters: {'num_leaves': 169, 'max_depth': 1, 'learning_rate': 0.12461343110070491, 'subsample': 0.679881731069803, 'colsample_bytree': 0.8794185703103987, 'min_child_samples': 36, 'reg_alpha': 2.510434968729898e-06, 'reg_lambda': 0.29382699841704435}. Best is trial 122 with value: -0.5253084186148224.

Early stopping, best iteration is:
[92]	valid_0's rmse: 33.3944	valid_0's l2: 1115.18

[I 2025-11-18 03:59:02,430] Trial 127 finished with value: -0.5261262010307104 and parameters: {'num_leaves': 166, 'max_depth': 1, 'learning_rate': 0.12573915206165537, 'subsample': 0.6852289325984573, 'colsample_bytree': 0.8839316537696519, 'min_child_samples': 36, 'reg_alpha': 1.569143147408929, 'reg_lambda': 3.2011607501097434}. Best is trial 122 with value: -0.5253084186148224.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:59:06,300] Trial 126 finished with value: -0.5251216629682605 and parameters: {'num_leaves': 172, 'max_depth': 1, 'learning_rate': 0.1224790857440655, 'subsample': 0.6854536924060876, 'colsample_bytree': 0.8761555787156108, 'min_child_samples': 48, 'reg_alpha': 1.0664525843173547e-06, 'reg_lambda': 5.298158244459934}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[83]	valid_0's rmse: 33.4263	valid_0's l2: 1117.32
Early stopping, best iteration is:
[178]	valid_0's rmse: 25.2141	valid_0's l2: 635.75
Early stopping, best iteration is:
[178]	valid_0's rmse: 25.4809	valid_0's l2: 649.279
Early stopping, best iteration is:
[82]	valid_0's rmse: 158.127	valid_0's l2: 25004.2

[I 2025-11-18 03:59:07,460] Trial 133 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[214]	valid_0's rmse: 154.449	valid_0's l2: 23854.4

[I 2025-11-18 03:59:08,273] Trial 135 pruned.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:59:08,635] Trial 130 finished with value: -0.5264584614980273 and parameters: {'num_leaves': 167, 'max_depth': 1, 'learning_rate': 0.11534134201440542, 'subsample': 0.6808228088295307, 'colsample_bytree': 0.8801590097004321, 'min_child_samples': 36, 'reg_alpha': 2.3231837442938365e-06, 'reg_lambda': 0.08319358663670622}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[154]	valid_0's rmse: 25.2924	valid_0's l2: 639.704
Early stopping, best iteration is:
[21]	valid_0's rmse: 33.4683	valid_0's l2: 1120.13
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[35]	valid_0's rmse: 26.2541	valid_0's l2: 689.277
Early stopping, best iteration is:
[172]	valid_0's rmse: 25.2509	valid_0's l2: 637.606
Early stopping, best iteration is:
[293]	valid_0's rmse: 154.56	valid_0's l2: 23888.7
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[423]	valid_0's rmse: 154.94	valid_0's l2: 24006.3
Early stopping, best iteration is:
[114]	valid_0's rmse: 25.0464	valid_0's l2: 627.321
Early stopping, best iteration is:
[93]	valid_0's rmse: 33.4576	valid_0's l2: 1119.41

[I 2025-11-18 03:59:13,425] Trial 128 finished with value: -0.525591743385495 and parameters: {'num_leaves': 181, 'max_depth': 1, 'learning_rate': 0.12678756190635587, 'subsample': 0.6674297289976958, 'colsample_bytree': 0.8776164549617695, 'min_child_samples': 36, 'reg_alpha': 1.4438199080283371e-06, 'reg_lambda': 4.104048387209269}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[330]	valid_0's rmse: 154.781	valid_0's l2: 23957.1

[I 2025-11-18 03:59:14,002] Trial 137 pruned.
[I 2025-11-18 03:59:14,356] Trial 136 pruned.

Early stopping, best iteration is:
[194]	valid_0's rmse: 25.2491	valid_0's l2: 637.517
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[192]	valid_0's rmse: 25.3929	valid_0's l2: 644.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[307]	valid_0's rmse: 154.25	valid_0's l2: 23793
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:59:18,580] Trial 139 pruned.

Early stopping, best iteration is:
[85]	valid_0's rmse: 157.54	valid_0's l2: 24818.8
Early stopping, best iteration is:
[235]	valid_0's rmse: 24.9933	valid_0's l2: 624.664
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:59:19,648] Trial 134 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[112]	valid_0's rmse: 24.805	valid_0's l2: 615.287
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[306]	valid_0's rmse: 154.753	valid_0's l2: 23948.5
Early stopping, best iteration is:
[291]	valid_0's rmse: 154.805	valid_0's l2: 23964.6

[I 2025-11-18 03:59:23,124] Trial 142 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[409]	valid_0's rmse: 154.362	valid_0's l2: 23827.5
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[202]	valid_0's rmse: 154.281	valid_0's l2: 23802.5
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[330]	valid_0's rmse: 154.143	valid_0's l2: 23760.2
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[306]	valid_0's rmse: 155.331	valid_0's l2: 24127.8
Early stopping, best iteration is:
[245]	valid_0's rmse: 154.245	valid_0's l2: 23791.5
Early stopping, best iteration is:
[25]	valid_0's rmse: 26.1412	valid_0's l2: 683.361
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:59:31,664] Trial 145 pruned.
[I 2025-11-18 03:59:32,067] Trial 147 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[45]	valid_0's rmse: 25.8339	valid_0's l2: 667.393
Early stopping, best iteration is:
[138]	valid_0's rmse: 33.1634	valid_0's l2: 1099.81

[I 2025-11-18 03:59:36,967] Trial 141 finished with value: -0.5336305714428914 and parameters: {'num_leaves': 153, 'max_depth': 2, 'learning_rate': 0.1114214688646335, 'subsample': 0.6832137061322983, 'colsample_bytree': 0.6995082308361726, 'min_child_samples': 45, 'reg_alpha': 8.79632065043023e-05, 'reg_lambda': 5.112110908255609}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[277]	valid_0's rmse: 154.395	valid_0's l2: 23837.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[556]	valid_0's rmse: 32.9776	valid_0's l2: 1087.52

[I 2025-11-18 03:59:40,884] Trial 138 finished with value: -0.5343224387263755 and parameters: {'num_leaves': 170, 'max_depth': 2, 'learning_rate': 0.11422972251651034, 'subsample': 0.6802731712560472, 'colsample_bytree': 0.6948857513414364, 'min_child_samples': 36, 'reg_alpha': 8.496000998699036e-05, 'reg_lambda': 1.5904054720742062}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[98]	valid_0's rmse: 157.577	valid_0's l2: 24830.4
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 03:59:42,450] Trial 140 pruned.

Early stopping, best iteration is:
[540]	valid_0's rmse: 154.485	valid_0's l2: 23865.7
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[310]	valid_0's rmse: 32.7019	valid_0's l2: 1069.42

[I 2025-11-18 03:59:46,709] Trial 146 finished with value: -0.5306108268126356 and parameters: {'num_leaves': 153, 'max_depth': 2, 'learning_rate': 0.15547603810858404, 'subsample': 0.691565461623539, 'colsample_bytree': 0.8779865096615592, 'min_child_samples': 36, 'reg_alpha': 3.085755322614247e-07, 'reg_lambda': 6.98982275379401}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[27]	valid_0's rmse: 26.1089	valid_0's l2: 681.672
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[610]	valid_0's rmse: 32.8665	valid_0's l2: 1080.2
Early stopping, best iteration is:
[25]	valid_0's rmse: 25.6496	valid_0's l2: 657.903

[I 2025-11-18 03:59:53,110] Trial 143 finished with value: -0.533688668983045 and parameters: {'num_leaves': 152, 'max_depth': 2, 'learning_rate': 0.11352477217898851, 'subsample': 0.6935407064111869, 'colsample_bytree': 0.6962337477682187, 'min_child_samples': 52, 'reg_alpha': 9.737851136940953e-06, 'reg_lambda': 1.5566419084712977}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[41]	valid_0's rmse: 157.176	valid_0's l2: 24704.3
Early stopping, best iteration is:
[53]	valid_0's rmse: 26.0146	valid_0's l2: 676.758

[I 2025-11-18 03:59:56,775] Trial 151 pruned.

Early stopping, best iteration is:
[237]	valid_0's rmse: 32.939	valid_0's l2: 1084.98

[I 2025-11-18 03:59:58,438] Trial 149 finished with value: -0.5300989004157961 and parameters: {'num_leaves': 141, 'max_depth': 2, 'learning_rate': 0.15540350166452346, 'subsample': 0.6922667562059744, 'colsample_bytree': 0.8869554480795983, 'min_child_samples': 54, 'reg_alpha': 4.739189994984715e-07, 'reg_lambda': 5.319742361318698}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[643]	valid_0's rmse: 32.9303	valid_0's l2: 1084.41
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[247]	valid_0's rmse: 33.0461	valid_0's l2: 1092.05

[I 2025-11-18 04:00:02,384] Trial 148 finished with value: -0.5319025112087202 and parameters: {'num_leaves': 151, 'max_depth': 2, 'learning_rate': 0.08517881770407003, 'subsample': 0.6917071217409215, 'colsample_bytree': 0.8807582051497691, 'min_child_samples': 54, 'reg_alpha': 7.426893546967223e-07, 'reg_lambda': 5.218508159125431}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[23]	valid_0's rmse: 26.4526	valid_0's l2: 699.741

[I 2025-11-18 04:00:03,104] Trial 144 finished with value: -0.5326386055401424 and parameters: {'num_leaves': 151, 'max_depth': 2, 'learning_rate': 0.11178503725806206, 'subsample': 0.6879964416045125, 'colsample_bytree': 0.8782615747193275, 'min_child_samples': 54, 'reg_alpha': 8.269269927307459e-05, 'reg_lambda': 5.317270284098188}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[24]	valid_0's rmse: 26.3349	valid_0's l2: 693.525
Early stopping, best iteration is:
[24]	valid_0's rmse: 26.3121	valid_0's l2: 692.324
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[23]	valid_0's rmse: 26.5006	valid_0's l2: 702.284
Early stopping, best iteration is:
[94]	valid_0's rmse: 157.648	valid_0's l2: 24852.9

[I 2025-11-18 04:00:15,554] Trial 150 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[38]	valid_0's rmse: 26.2994	valid_0's l2: 691.658
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[43]	valid_0's rmse: 26.2613	valid_0's l2: 689.653
Early stopping, best iteration is:
[46]	valid_0's rmse: 26.4847	valid_0's l2: 701.441
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[51]	valid_0's rmse: 155.693	valid_0's l2: 24240.2

[I 2025-11-18 04:00:28,333] Trial 153 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[34]	valid_0's rmse: 25.915	valid_0's l2: 671.59
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[29]	valid_0's rmse: 26.4719	valid_0's l2: 700.759
Early stopping, best iteration is:
[53]	valid_0's rmse: 155.706	valid_0's l2: 24244.3

[I 2025-11-18 04:00:39,481] Trial 154 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[36]	valid_0's rmse: 25.9007	valid_0's l2: 670.847
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[44]	valid_0's rmse: 25.66	valid_0's l2: 658.438
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[42]	valid_0's rmse: 155.761	valid_0's l2: 24261.6
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[44]	valid_0's rmse: 156.133	valid_0's l2: 24377.5

[I 2025-11-18 04:00:51,104] Trial 157 pruned.

Early stopping, best iteration is:
[31]	valid_0's rmse: 26.1454	valid_0's l2: 683.58
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[60]	valid_0's rmse: 157.851	valid_0's l2: 24917
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[86]	valid_0's rmse: 156.177	valid_0's l2: 24391.3

[I 2025-11-18 04:00:57,766] Trial 152 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[43]	valid_0's rmse: 156.209	valid_0's l2: 24401.2
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[72]	valid_0's rmse: 157.817	valid_0's l2: 24906.2
Early stopping, best iteration is:
[36]	valid_0's rmse: 26.5759	valid_0's l2: 706.277
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[79]	valid_0's rmse: 155.696	valid_0's l2: 24241.3
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 25.9035	valid_0's l2: 670.994

[I 2025-11-18 04:01:12,944] Trial 159 pruned.

Early stopping, best iteration is:
[71]	valid_0's rmse: 155.885	valid_0's l2: 24300.1
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:01:15,507] Trial 160 pruned.

Early stopping, best iteration is:
[29]	valid_0's rmse: 26.1334	valid_0's l2: 682.957
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 157.059	valid_0's l2: 24667.4

[I 2025-11-18 04:01:23,349] Trial 161 pruned.

Early stopping, best iteration is:
[493]	valid_0's rmse: 24.1391	valid_0's l2: 582.695
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[22]	valid_0's rmse: 26.2146	valid_0's l2: 687.204
Early stopping, best iteration is:
[48]	valid_0's rmse: 156.181	valid_0's l2: 24392.5
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[21]	valid_0's rmse: 34.3899	valid_0's l2: 1182.67

[I 2025-11-18 04:01:29,843] Trial 155 finished with value: -0.5487495118803777 and parameters: {'num_leaves': 174, 'max_depth': 0, 'learning_rate': 0.15441203560659533, 'subsample': 0.709528882033807, 'colsample_bytree': 0.9013098419268608, 'min_child_samples': 53, 'reg_alpha': 5.897677980528914e-07, 'reg_lambda': 7.424059665153319}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 156.199	valid_0's l2: 24398.2
Early stopping, best iteration is:
[19]	valid_0's rmse: 33.8697	valid_0's l2: 1147.15
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 25.4232	valid_0's l2: 646.341

[I 2025-11-18 04:01:33,655] Trial 156 finished with value: -0.5491843669058235 and parameters: {'num_leaves': 165, 'max_depth': 0, 'learning_rate': 0.1562393675410579, 'subsample': 0.7070185415780725, 'colsample_bytree': 0.8981000463986815, 'min_child_samples': 32, 'reg_alpha': 7.612192920746977e-07, 'reg_lambda': 7.1058041832494645}. Best is trial 126 with value: -0.5251216629682605.
[I 2025-11-18 04:01:34,141] Trial 164 pruned.

Early stopping, best iteration is:
[76]	valid_0's rmse: 156.921	valid_0's l2: 24624.3
Early stopping, best iteration is:
[502]	valid_0's rmse: 24.1465	valid_0's l2: 583.054
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[51]	valid_0's rmse: 157.172	valid_0's l2: 24702.9
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[18]	valid_0's rmse: 34.811	valid_0's l2: 1211.81

[I 2025-11-18 04:01:38,868] Trial 158 finished with value: -0.5513841593340731 and parameters: {'num_leaves': 175, 'max_depth': 0, 'learning_rate': 0.15579642414840503, 'subsample': 0.708245709158418, 'colsample_bytree': 0.8961403085921488, 'min_child_samples': 52, 'reg_alpha': 6.942803015107258e-07, 'reg_lambda': 7.176922604899671}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[36]	valid_0's rmse: 33.8049	valid_0's l2: 1142.77

[I 2025-11-18 04:01:42,991] Trial 162 finished with value: -0.549876972010154 and parameters: {'num_leaves': 161, 'max_depth': 13, 'learning_rate': 0.08933456796571876, 'subsample': 0.6403313163746184, 'colsample_bytree': 0.9021600980692176, 'min_child_samples': 32, 'reg_alpha': 2.828812870258096e-06, 'reg_lambda': 2.4578822416275545}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 166.652	valid_0's l2: 27773
Early stopping, best iteration is:
[40]	valid_0's rmse: 157.069	valid_0's l2: 24670.7

[I 2025-11-18 04:01:45,737] Trial 167 pruned.

Early stopping, best iteration is:
[539]	valid_0's rmse: 24.1718	valid_0's l2: 584.274

[I 2025-11-18 04:01:47,417] Trial 170 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[55]	valid_0's rmse: 157.042	valid_0's l2: 24662

[I 2025-11-18 04:01:54,525] Trial 168 pruned.
[I 2025-11-18 04:01:55,054] Trial 165 finished with value: -0.5452684278477892 and parameters: {'num_leaves': 164, 'max_depth': 0, 'learning_rate': 0.14223359451767262, 'subsample': 0.6391579748877685, 'colsample_bytree': 0.900641834565646, 'min_child_samples': 40, 'reg_alpha': 2.766410175987106e-06, 'reg_lambda': 2.3771553958034026}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[14]	valid_0's rmse: 34.2698	valid_0's l2: 1174.42
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[827]	valid_0's rmse: 23.8976	valid_0's l2: 571.094
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[988]	valid_0's rmse: 153.811	valid_0's l2: 23657.8
Early stopping, best iteration is:
[46]	valid_0's rmse: 158.006	valid_0's l2: 24965.8

[I 2025-11-18 04:01:58,525] Trial 169 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 26.7675	valid_0's l2: 716.5
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[529]	valid_0's rmse: 24.1432	valid_0's l2: 582.892
Did not meet early stopping. Best iteration is:
[904]	valid_0's rmse: 23.9805	valid_0's l2: 575.065
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[21]	valid_0's rmse: 33.9266	valid_0's l2: 1151.02

[I 2025-11-18 04:02:04,135] Trial 166 finished with value: -0.5470969018152063 and parameters: {'num_leaves': 164, 'max_depth': 0, 'learning_rate': 0.13919068282777167, 'subsample': 0.6438159173350841, 'colsample_bytree': 0.8959700881572548, 'min_child_samples': 33, 'reg_alpha': 2.7155257389339445e-06, 'reg_lambda': 2.880209288936424}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[26]	valid_0's rmse: 34.1958	valid_0's l2: 1169.35

[I 2025-11-18 04:02:04,990] Trial 163 finished with value: -0.5499179541959717 and parameters: {'num_leaves': 175, 'max_depth': 0, 'learning_rate': 0.08715474543530062, 'subsample': 0.6400457198408308, 'colsample_bytree': 0.9042087434295074, 'min_child_samples': 33, 'reg_alpha': 2.4154052295816097e-06, 'reg_lambda': 2.378445632193454}. Best is trial 126 with value: -0.5251216629682605.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[617]	valid_0's rmse: 23.9566	valid_0's l2: 573.921
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:08,202] Trial 171 finished with value: -0.5269149947621913 and parameters: {'num_leaves': 159, 'max_depth': 1, 'learning_rate': 0.13697227477666402, 'subsample': 0.9768830111944976, 'colsample_bytree': 0.8628612816565692, 'min_child_samples': 40, 'reg_alpha': 2.8621033795861936e-06, 'reg_lambda': 2.831643103112791}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[70]	valid_0's rmse: 33.4932	valid_0's l2: 1121.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[858]	valid_0's rmse: 23.9471	valid_0's l2: 573.465
Early stopping, best iteration is:
[534]	valid_0's rmse: 23.8508	valid_0's l2: 568.861
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 160.345	valid_0's l2: 25710.4
Early stopping, best iteration is:
[626]	valid_0's rmse: 24.1258	valid_0's l2: 582.055
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:12,922] Trial 172 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[962]	valid_0's rmse: 153.901	valid_0's l2: 23685.5
Did not meet early stopping. Best iteration is:
[993]	valid_0's rmse: 153.726	valid_0's l2: 23631.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[539]	valid_0's rmse: 23.908	valid_0's l2: 571.595
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 25.119	valid_0's l2: 630.963
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 25.0259	valid_0's l2: 626.296
Early stopping, best iteration is:
[869]	valid_0's rmse: 23.9685	valid_0's l2: 574.49
Early stopping, best iteration is:
[494]	valid_0's rmse: 23.9614	valid_0's l2: 574.149
Did not meet early stopping. Best iteration is:
[980]	valid_0's rmse: 153.788	valid_0's l2: 23650.9
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:27,238] Trial 173 finished with value: -0.5272095794957006 and parameters: {'num_leaves': 119, 'max_depth': 1, 'learning_rate': 0.13497316920574806, 'subsample': 0.652274927491886, 'colsample_bytree': 0.8599051461557081, 'min_child_samples': 32, 'reg_alpha': 2.473276900734196e-06, 'reg_lambda': 3.2392524180432463}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[84]	valid_0's rmse: 33.5207	valid_0's l2: 1123.64

[I 2025-11-18 04:02:27,621] Trial 174 finished with value: -0.5268960801341495 and parameters: {'num_leaves': 182, 'max_depth': 1, 'learning_rate': 0.1372246696406032, 'subsample': 0.6513241684083929, 'colsample_bytree': 0.8628949743933271, 'min_child_samples': 32, 'reg_alpha': 2.461512005676726e-06, 'reg_lambda': 3.304226656749299}. Best is trial 126 with value: -0.5251216629682605.

Early stopping, best iteration is:
[70]	valid_0's rmse: 33.4659	valid_0's l2: 1119.97
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[995]	valid_0's rmse: 153.944	valid_0's l2: 23698.6
Did not meet early stopping. Best iteration is:
[963]	valid_0's rmse: 154.177	valid_0's l2: 23770.6
Did not meet early stopping. Best iteration is:
[994]	valid_0's rmse: 153.96	valid_0's l2: 23703.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[86]	valid_0's rmse: 33.3893	valid_0's l2: 1114.85

[I 2025-11-18 04:02:37,757] Trial 176 finished with value: -0.5248754661043161 and parameters: {'num_leaves': 182, 'max_depth': 1, 'learning_rate': 0.1376487510667218, 'subsample': 0.6646570414741191, 'colsample_bytree': 0.8579018466891751, 'min_child_samples': 48, 'reg_alpha': 2.5033847143506212e-05, 'reg_lambda': 3.188772872548122}. Best is trial 176 with value: -0.5248754661043161.

Did not meet early stopping. Best iteration is:
[978]	valid_0's rmse: 154.144	valid_0's l2: 23760.5
Early stopping, best iteration is:
[319]	valid_0's rmse: 23.9853	valid_0's l2: 575.294
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 186.44	valid_0's l2: 34759.9
Early stopping, best iteration is:
[409]	valid_0's rmse: 24.0036	valid_0's l2: 576.174
Did not meet early stopping. Best iteration is:
[982]	valid_0's rmse: 153.79	valid_0's l2: 23651.5
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:40,767] Trial 177 finished with value: -0.5261968448477292 and parameters: {'num_leaves': 179, 'max_depth': 1, 'learning_rate': 0.13921648057792665, 'subsample': 0.6685125599317141, 'colsample_bytree': 0.8640429539421588, 'min_child_samples': 47, 'reg_alpha': 2.4454759410941846e-05, 'reg_lambda': 3.273560414809963}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[16]	valid_0's rmse: 33.5205	valid_0's l2: 1123.63

[I 2025-11-18 04:02:41,121] Trial 175 pruned.
[I 2025-11-18 04:02:41,387] Trial 178 finished with value: -0.5269223925469104 and parameters: {'num_leaves': 184, 'max_depth': 1, 'learning_rate': 0.13727128963358454, 'subsample': 0.6648319894186433, 'colsample_bytree': 0.8605365021818467, 'min_child_samples': 40, 'reg_alpha': 3.398712527868827e-05, 'reg_lambda': 4.25637505491054}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[84]	valid_0's rmse: 33.4351	valid_0's l2: 1117.91
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:41,998] Trial 180 finished with value: -0.5260071128673736 and parameters: {'num_leaves': 183, 'max_depth': 1, 'learning_rate': 0.13694767885478537, 'subsample': 0.6643945706118682, 'colsample_bytree': 0.7238539538412168, 'min_child_samples': 48, 'reg_alpha': 3.246687337460013e-05, 'reg_lambda': 3.5731917528620394}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[81]	valid_0's rmse: 33.4255	valid_0's l2: 1117.26
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:45,020] Trial 181 finished with value: -0.5274336501823592 and parameters: {'num_leaves': 181, 'max_depth': 1, 'learning_rate': 0.13360926097120793, 'subsample': 0.6691681875821279, 'colsample_bytree': 0.7254692898437283, 'min_child_samples': 47, 'reg_alpha': 2.4768299131608488e-05, 'reg_lambda': 4.325052552039735}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[24]	valid_0's rmse: 33.5171	valid_0's l2: 1123.4
Did not meet early stopping. Best iteration is:
[984]	valid_0's rmse: 153.867	valid_0's l2: 23675.1
Did not meet early stopping. Best iteration is:
[984]	valid_0's rmse: 153.803	valid_0's l2: 23655.5
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:48,714] Trial 182 finished with value: -0.5285542802857058 and parameters: {'num_leaves': 182, 'max_depth': 1, 'learning_rate': 0.1864971481516409, 'subsample': 0.6667175102353189, 'colsample_bytree': 0.8553509499197862, 'min_child_samples': 48, 'reg_alpha': 2.3129546888556466e-05, 'reg_lambda': 3.845279218045504}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[59]	valid_0's rmse: 34.4222	valid_0's l2: 1184.89
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[447]	valid_0's rmse: 23.9	valid_0's l2: 571.211
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[992]	valid_0's rmse: 154.086	valid_0's l2: 23742.5
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 158.011	valid_0's l2: 24967.5
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 158.038	valid_0's l2: 24976
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[417]	valid_0's rmse: 23.9891	valid_0's l2: 575.475

[I 2025-11-18 04:02:53,869] Trial 183 pruned.
[I 2025-11-18 04:02:54,388] Trial 184 pruned.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[968]	valid_0's rmse: 154.268	valid_0's l2: 23798.6
Early stopping, best iteration is:
[80]	valid_0's rmse: 34.4475	valid_0's l2: 1186.63
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:54,849] Trial 186 finished with value: -0.5290523188598172 and parameters: {'num_leaves': 181, 'max_depth': 1, 'learning_rate': 0.18963099288020696, 'subsample': 0.9750764959811586, 'colsample_bytree': 0.6849511889847273, 'min_child_samples': 48, 'reg_alpha': 2.5170106340588988e-05, 'reg_lambda': 4.052019976034789}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[454]	valid_0's rmse: 23.8926	valid_0's l2: 570.854

[I 2025-11-18 04:02:55,577] Trial 179 finished with value: -0.5256443558287459 and parameters: {'num_leaves': 183, 'max_depth': 1, 'learning_rate': 0.1334900570117386, 'subsample': 0.6663202409629965, 'colsample_bytree': 0.8616569497095333, 'min_child_samples': 47, 'reg_alpha': 1.2839318630743455e-08, 'reg_lambda': 3.1509745862022682}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[79]	valid_0's rmse: 33.4719	valid_0's l2: 1120.37
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[626]	valid_0's rmse: 23.8871	valid_0's l2: 570.594
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:02:58,563] Trial 187 finished with value: -0.5286717431057183 and parameters: {'num_leaves': 180, 'max_depth': 1, 'learning_rate': 0.18609128071885023, 'subsample': 0.972806469698945, 'colsample_bytree': 0.6833978216287153, 'min_child_samples': 47, 'reg_alpha': 3.223183863343144e-05, 'reg_lambda': 3.63110228818972}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[46]	valid_0's rmse: 34.1441	valid_0's l2: 1165.82
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[707]	valid_0's rmse: 23.7804	valid_0's l2: 565.509
Early stopping, best iteration is:
[855]	valid_0's rmse: 23.9129	valid_0's l2: 571.826
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[111]	valid_0's rmse: 33.4612	valid_0's l2: 1119.65

[I 2025-11-18 04:03:04,670] Trial 185 finished with value: -0.5263636819126101 and parameters: {'num_leaves': 181, 'max_depth': 1, 'learning_rate': 0.10213365854668113, 'subsample': 0.6657137183420997, 'colsample_bytree': 0.857211586523554, 'min_child_samples': 48, 'reg_alpha': 2.4150005236099986e-05, 'reg_lambda': 4.227907173805467}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[968]	valid_0's rmse: 153.738	valid_0's l2: 23635.5
Did not meet early stopping. Best iteration is:
[996]	valid_0's rmse: 153.658	valid_0's l2: 23610.9
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 25.1454	valid_0's l2: 632.289
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[655]	valid_0's rmse: 24.1829	valid_0's l2: 584.811
Early stopping, best iteration is:
[817]	valid_0's rmse: 23.9307	valid_0's l2: 572.677
Early stopping, best iteration is:
[721]	valid_0's rmse: 24.075	valid_0's l2: 579.605
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:03:13,981] Trial 189 finished with value: -0.5290463460338901 and parameters: {'num_leaves': 183, 'max_depth': 1, 'learning_rate': 0.18596458592824477, 'subsample': 0.975991713444885, 'colsample_bytree': 0.8603844132960912, 'min_child_samples': 29, 'reg_alpha': 3.807378167073346e-05, 'reg_lambda': 3.560069166951276}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[56]	valid_0's rmse: 34.339	valid_0's l2: 1179.17
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[55]	valid_0's rmse: 34.4838	valid_0's l2: 1189.14

[I 2025-11-18 04:03:15,365] Trial 188 finished with value: -0.5296033410317049 and parameters: {'num_leaves': 121, 'max_depth': 1, 'learning_rate': 0.19266690863635452, 'subsample': 0.979461369991204, 'colsample_bytree': 0.8562589860225569, 'min_child_samples': 29, 'reg_alpha': 2.3738917927777885e-05, 'reg_lambda': 3.3564368452662423}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[842]	valid_0's rmse: 23.9259	valid_0's l2: 572.449
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[935]	valid_0's rmse: 153.788	valid_0's l2: 23650.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[897]	valid_0's rmse: 24.0109	valid_0's l2: 576.525
Did not meet early stopping. Best iteration is:
[983]	valid_0's rmse: 153.745	valid_0's l2: 23637.5
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[853]	valid_0's rmse: 23.9644	valid_0's l2: 574.292
Did not meet early stopping. Best iteration is:
[985]	valid_0's rmse: 153.65	valid_0's l2: 23608.4
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:03:27,600] Trial 190 finished with value: -0.5285256768313672 and parameters: {'num_leaves': 120, 'max_depth': 1, 'learning_rate': 0.18129170097502134, 'subsample': 0.6621574582585991, 'colsample_bytree': 0.8503055948418978, 'min_child_samples': 49, 'reg_alpha': 1.5462232683958816e-06, 'reg_lambda': 4.160103377657648}. Best is trial 176 with value: -0.5248754661043161.

Did not meet early stopping. Best iteration is:
[996]	valid_0's rmse: 154.356	valid_0's l2: 23825.9
Early stopping, best iteration is:
[65]	valid_0's rmse: 34.3309	valid_0's l2: 1178.61
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:03:29,787] Trial 194 finished with value: -0.5278254709990412 and parameters: {'num_leaves': 182, 'max_depth': 1, 'learning_rate': 0.18402223233329426, 'subsample': 0.6736583099643488, 'colsample_bytree': 0.7230249294593196, 'min_child_samples': 49, 'reg_alpha': 2.938597276070596e-05, 'reg_lambda': 4.388825436584093}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[56]	valid_0's rmse: 34.1797	valid_0's l2: 1168.25
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[998]	valid_0's rmse: 153.769	valid_0's l2: 23645
Early stopping, best iteration is:
[55]	valid_0's rmse: 34.532	valid_0's l2: 1192.46

[I 2025-11-18 04:03:36,025] Trial 192 finished with value: -0.5296799610417515 and parameters: {'num_leaves': 88, 'max_depth': 1, 'learning_rate': 0.19183098090728873, 'subsample': 0.6642664719466166, 'colsample_bytree': 0.8505808567616723, 'min_child_samples': 47, 'reg_alpha': 3.677655689407487e-05, 'reg_lambda': 3.880467835462688}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 154.672	valid_0's l2: 23923.5
Early stopping, best iteration is:
[122]	valid_0's rmse: 33.4871	valid_0's l2: 1121.39
Did not meet early stopping. Best iteration is:
[973]	valid_0's rmse: 153.747	valid_0's l2: 23638

[I 2025-11-18 04:03:39,222] Trial 193 finished with value: -0.5262310632606756 and parameters: {'num_leaves': 185, 'max_depth': 1, 'learning_rate': 0.1015507199582996, 'subsample': 0.6642056646652167, 'colsample_bytree': 0.7195027016085209, 'min_child_samples': 48, 'reg_alpha': 3.62507303584512e-05, 'reg_lambda': 4.439559936267598}. Best is trial 176 with value: -0.5248754661043161.

Did not meet early stopping. Best iteration is:
[988]	valid_0's rmse: 154.095	valid_0's l2: 23745.2
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 34.9942	valid_0's l2: 1224.59
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[995]	valid_0's rmse: 154.193	valid_0's l2: 23775.5
Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 158.357	valid_0's l2: 25076.9
Early stopping, best iteration is:
[38]	valid_0's rmse: 26.0598	valid_0's l2: 679.114
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:03:42,307] Trial 191 finished with value: -0.5280067860558713 and parameters: {'num_leaves': 72, 'max_depth': 1, 'learning_rate': 0.19536329338021477, 'subsample': 0.6601789879130376, 'colsample_bytree': 0.8505242278714005, 'min_child_samples': 47, 'reg_alpha': 3.084765322504945e-05, 'reg_lambda': 4.04837159548864}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[43]	valid_0's rmse: 34.2263	valid_0's l2: 1171.44
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[40]	valid_0's rmse: 26.4756	valid_0's l2: 700.96
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[639]	valid_0's rmse: 24.0828	valid_0's l2: 579.983
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:03:48,156] Trial 199 finished with value: -0.5275753748986459 and parameters: {'num_leaves': 170, 'max_depth': 1, 'learning_rate': 0.09916544697916396, 'subsample': 0.6593164597927536, 'colsample_bytree': 0.871753878449552, 'min_child_samples': 39, 'reg_alpha': 4.396089292535545e-05, 'reg_lambda': 0.664278073211794}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[22]	valid_0's rmse: 33.4756	valid_0's l2: 1120.61
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[60]	valid_0's rmse: 34.3762	valid_0's l2: 1181.73

[I 2025-11-18 04:03:49,669] Trial 195 finished with value: -0.5278423505985802 and parameters: {'num_leaves': 183, 'max_depth': 1, 'learning_rate': 0.18406080223787116, 'subsample': 0.6640268221299181, 'colsample_bytree': 0.8504272501002136, 'min_child_samples': 50, 'reg_alpha': 3.96328286496813e-05, 'reg_lambda': 4.080864868705473}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[119]	valid_0's rmse: 33.5821	valid_0's l2: 1127.76

[I 2025-11-18 04:03:50,224] Trial 197 finished with value: -0.5272033248968896 and parameters: {'num_leaves': 170, 'max_depth': 1, 'learning_rate': 0.09940468627684204, 'subsample': 0.6577746670513048, 'colsample_bytree': 0.6857518709679734, 'min_child_samples': 50, 'reg_alpha': 4.782995678179255e-05, 'reg_lambda': 4.671550800092576}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[984]	valid_0's rmse: 154.357	valid_0's l2: 23825.9
Early stopping, best iteration is:
[112]	valid_0's rmse: 33.4594	valid_0's l2: 1119.53

[I 2025-11-18 04:03:53,643] Trial 196 finished with value: -0.5404817782180541 and parameters: {'num_leaves': 184, 'max_depth': 1, 'learning_rate': 0.02270218015140999, 'subsample': 0.6597156930785579, 'colsample_bytree': 0.8701253689208865, 'min_child_samples': 49, 'reg_alpha': 4.912511296274622e-05, 'reg_lambda': 9.5658115353471}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[122]	valid_0's rmse: 33.4068	valid_0's l2: 1116.01

[I 2025-11-18 04:03:53,976] Trial 198 finished with value: -0.5267454896179223 and parameters: {'num_leaves': 171, 'max_depth': 1, 'learning_rate': 0.10168416311733401, 'subsample': 0.6608574703260542, 'colsample_bytree': 0.8690886785594077, 'min_child_samples': 38, 'reg_alpha': 5.1164924467624726e-05, 'reg_lambda': 3.157806697683026}. Best is trial 176 with value: -0.5248754661043161.

Did not meet early stopping. Best iteration is:
[1000]	valid_0's rmse: 154.254	valid_0's l2: 23794.3
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[901]	valid_0's rmse: 24.0238	valid_0's l2: 577.144
Early stopping, best iteration is:
[43]	valid_0's rmse: 26.2153	valid_0's l2: 687.24
Early stopping, best iteration is:
[856]	valid_0's rmse: 23.9721	valid_0's l2: 574.663
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[215]	valid_0's rmse: 25.1893	valid_0's l2: 634.501
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:04:03,439] Trial 200 finished with value: -0.5263741330382719 and parameters: {'num_leaves': 170, 'max_depth': 1, 'learning_rate': 0.10580231305342434, 'subsample': 0.6578680227807077, 'colsample_bytree': 0.8704946040260152, 'min_child_samples': 50, 'reg_alpha': 9.623469421029313e-06, 'reg_lambda': 9.692860405760293}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[22]	valid_0's rmse: 33.5427	valid_0's l2: 1125.11
Did not meet early stopping. Best iteration is:
[993]	valid_0's rmse: 154.258	valid_0's l2: 23795.4
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[924]	valid_0's rmse: 24.0404	valid_0's l2: 577.94
Early stopping, best iteration is:
[111]	valid_0's rmse: 33.4563	valid_0's l2: 1119.32

[I 2025-11-18 04:04:05,011] Trial 201 finished with value: -0.5267633479792788 and parameters: {'num_leaves': 171, 'max_depth': 1, 'learning_rate': 0.10218602708603965, 'subsample': 0.6593591421947359, 'colsample_bytree': 0.8684864600955308, 'min_child_samples': 43, 'reg_alpha': 8.391816064281058e-06, 'reg_lambda': 9.479916673907274}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[56]	valid_0's rmse: 25.8065	valid_0's l2: 665.976
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:04:13,150] Trial 202 finished with value: -0.5266620598685022 and parameters: {'num_leaves': 193, 'max_depth': 1, 'learning_rate': 0.09995125236513466, 'subsample': 0.6581331315566822, 'colsample_bytree': 0.8687829309124617, 'min_child_samples': 50, 'reg_alpha': 5.435111218395504e-05, 'reg_lambda': 4.71184203669284}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[22]	valid_0's rmse: 33.5497	valid_0's l2: 1125.58
Early stopping, best iteration is:
[207]	valid_0's rmse: 25.1383	valid_0's l2: 631.935
Early stopping, best iteration is:
[52]	valid_0's rmse: 25.8737	valid_0's l2: 669.446
Did not meet early stopping. Best iteration is:
[993]	valid_0's rmse: 154.208	valid_0's l2: 23780.2
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[34]	valid_0's rmse: 26.8958	valid_0's l2: 723.384
Early stopping, best iteration is:
[336]	valid_0's rmse: 154.366	valid_0's l2: 23828.9
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[45]	valid_0's rmse: 26.3019	valid_0's l2: 691.79
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:04:21,500] Trial 35 finished with value: -0.583472141515883 and parameters: {'num_leaves': 247, 'max_depth': -1, 'learning_rate': 0.001313477182955546, 'subsample': 0.9515163249693, 'colsample_bytree': 0.8719510991078692, 'min_child_samples': 52, 'reg_alpha': 0.00010979566655108513, 'reg_lambda': 0.009653735662492325}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 159.461	valid_0's l2: 25427.9
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[35]	valid_0's rmse: 25.9352	valid_0's l2: 672.635
Early stopping, best iteration is:
[56]	valid_0's rmse: 26.1159	valid_0's l2: 682.039
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[73]	valid_0's rmse: 156.022	valid_0's l2: 24342.9
Did not meet early stopping. Best iteration is:
[967]	valid_0's rmse: 154.275	valid_0's l2: 23800.7
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[113]	valid_0's rmse: 33.3978	valid_0's l2: 1115.41

[I 2025-11-18 04:04:27,835] Trial 206 finished with value: -0.5267864290935965 and parameters: {'num_leaves': 194, 'max_depth': 1, 'learning_rate': 0.1021899055728979, 'subsample': 0.6726071354749189, 'colsample_bytree': 0.8709624129378765, 'min_child_samples': 38, 'reg_alpha': 1.3230018388987065e-08, 'reg_lambda': 3.02712256709697}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[65]	valid_0's rmse: 33.2377	valid_0's l2: 1104.75

[I 2025-11-18 04:04:28,414] Trial 212 finished with value: -0.5337600979854585 and parameters: {'num_leaves': 193, 'max_depth': 2, 'learning_rate': 0.10029276432973039, 'subsample': 0.6739012632220359, 'colsample_bytree': 0.863841765090788, 'min_child_samples': 44, 'reg_alpha': 1.9422668500387065e-07, 'reg_lambda': 3.0489519118146418}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[192]	valid_0's rmse: 25.0885	valid_0's l2: 629.431
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[62]	valid_0's rmse: 156.216	valid_0's l2: 24403.4
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:04:33,953] Trial 204 pruned.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[983]	valid_0's rmse: 154.252	valid_0's l2: 23793.7
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[974]	valid_0's rmse: 154.365	valid_0's l2: 23828.5
Early stopping, best iteration is:
[180]	valid_0's rmse: 25.0578	valid_0's l2: 627.892
Early stopping, best iteration is:
[425]	valid_0's rmse: 155.048	valid_0's l2: 24039.8
Early stopping, best iteration is:
[101]	valid_0's rmse: 33.4151	valid_0's l2: 1116.57
Early stopping, best iteration is:
[34]	valid_0's rmse: 32.9449	valid_0's l2: 1085.36

[I 2025-11-18 04:04:39,117] Trial 208 finished with value: -0.5262203949698726 and parameters: {'num_leaves': 191, 'max_depth': 1, 'learning_rate': 0.10332247451782474, 'subsample': 0.6577184356877538, 'colsample_bytree': 0.8672660239086145, 'min_child_samples': 51, 'reg_alpha': 3.990750580103631e-08, 'reg_lambda': 3.0643998024085417}. Best is trial 176 with value: -0.5248754661043161.
[I 2025-11-18 04:04:39,182] Trial 216 pruned.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[175]	valid_0's rmse: 157.099	valid_0's l2: 24680.1

[I 2025-11-18 04:04:39,304] Trial 213 finished with value: -0.5445903491675481 and parameters: {'num_leaves': 190, 'max_depth': 6, 'learning_rate': 0.10724108067855435, 'subsample': 0.6706228978791744, 'colsample_bytree': 0.705994557718785, 'min_child_samples': 44, 'reg_alpha': 1.1857983516176844e-08, 'reg_lambda': 2.9873647238051753}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:04:40,412] Trial 215 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[235]	valid_0's rmse: 25.4309	valid_0's l2: 646.732
Early stopping, best iteration is:
[42]	valid_0's rmse: 26.3056	valid_0's l2: 691.984
Early stopping, best iteration is:
[61]	valid_0's rmse: 156.66	valid_0's l2: 24542.3
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[140]	valid_0's rmse: 159.406	valid_0's l2: 25410.4
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[174]	valid_0's rmse: 25.3429	valid_0's l2: 642.263

[I 2025-11-18 04:04:48,557] Trial 217 pruned.

Early stopping, best iteration is:
[377]	valid_0's rmse: 154.754	valid_0's l2: 23948.8
Early stopping, best iteration is:
[113]	valid_0's rmse: 33.3845	valid_0's l2: 1114.52
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:04:49,147] Trial 209 finished with value: -0.5265205363694089 and parameters: {'num_leaves': 191, 'max_depth': 1, 'learning_rate': 0.1005054945400631, 'subsample': 0.6737581525260227, 'colsample_bytree': 0.8664858828263995, 'min_child_samples': 43, 'reg_alpha': 5.655181006996975e-05, 'reg_lambda': 4.883057768273846}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[102]	valid_0's rmse: 33.4206	valid_0's l2: 1116.93
Early stopping, best iteration is:
[248]	valid_0's rmse: 25.4668	valid_0's l2: 648.558

[I 2025-11-18 04:04:49,394] Trial 207 finished with value: -0.5267236283475594 and parameters: {'num_leaves': 171, 'max_depth': 1, 'learning_rate': 0.10228359208933568, 'subsample': 0.6582220676496761, 'colsample_bytree': 0.8638648770574899, 'min_child_samples': 43, 'reg_alpha': 1.033686756151848e-05, 'reg_lambda': 9.901037485335456}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[283]	valid_0's rmse: 25.3001	valid_0's l2: 640.096
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[283]	valid_0's rmse: 25.3065	valid_0's l2: 640.418
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[154]	valid_0's rmse: 25.0938	valid_0's l2: 629.696
Early stopping, best iteration is:
[159]	valid_0's rmse: 25.0591	valid_0's l2: 627.961
Early stopping, best iteration is:
[149]	valid_0's rmse: 25.2187	valid_0's l2: 635.981
Early stopping, best iteration is:
[64]	valid_0's rmse: 158.128	valid_0's l2: 25004.4
Early stopping, best iteration is:
[486]	valid_0's rmse: 155.063	valid_0's l2: 24044.6
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[72]	valid_0's rmse: 157.058	valid_0's l2: 24667.2

[I 2025-11-18 04:05:01,902] Trial 211 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[438]	valid_0's rmse: 154.724	valid_0's l2: 23939.5
Early stopping, best iteration is:
[64]	valid_0's rmse: 158.04	valid_0's l2: 24976.6

[I 2025-11-18 04:05:06,144] Trial 214 pruned.
[I 2025-11-18 04:05:06,556] Trial 224 pruned.

Early stopping, best iteration is:
[24]	valid_0's rmse: 34.3174	valid_0's l2: 1177.69

[I 2025-11-18 04:05:07,650] Trial 203 finished with value: -0.5462635260285184 and parameters: {'num_leaves': 191, 'max_depth': -1, 'learning_rate': 0.10065736639180839, 'subsample': 0.6577395328976201, 'colsample_bytree': 0.8497398390300731, 'min_child_samples': 50, 'reg_alpha': 6.624631056447481e-08, 'reg_lambda': 3.1164802794516073}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[136]	valid_0's rmse: 25.2521	valid_0's l2: 637.67
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[546]	valid_0's rmse: 154.184	valid_0's l2: 23772.8
Early stopping, best iteration is:
[236]	valid_0's rmse: 154.056	valid_0's l2: 23733.2

[I 2025-11-18 04:05:11,126] Trial 222 pruned.

Early stopping, best iteration is:
[249]	valid_0's rmse: 154.225	valid_0's l2: 23785.3
Early stopping, best iteration is:
[325]	valid_0's rmse: 154.68	valid_0's l2: 23925.8Early stopping, best iteration is:
[112]	valid_0's rmse: 158.189	valid_0's l2: 25023.7

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[149]	valid_0's rmse: 25.2796	valid_0's l2: 639.057
Early stopping, best iteration is:
[650]	valid_0's rmse: 154.911	valid_0's l2: 23997.4
Early stopping, best iteration is:
[293]	valid_0's rmse: 25.5809	valid_0's l2: 654.383
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[634]	valid_0's rmse: 154.769	valid_0's l2: 23953.5
Early stopping, best iteration is:
[162]	valid_0's rmse: 25.2899	valid_0's l2: 639.578

[I 2025-11-18 04:05:16,751] Trial 221 pruned.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:05:17,802] Trial 223 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[543]	valid_0's rmse: 154.773	valid_0's l2: 23954.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[24]	valid_0's rmse: 34.4187	valid_0's l2: 1184.65

[I 2025-11-18 04:05:21,651] Trial 205 finished with value: -0.5486705672471556 and parameters: {'num_leaves': 194, 'max_depth': -1, 'learning_rate': 0.10411511369374263, 'subsample': 0.6748566937265772, 'colsample_bytree': 0.8483610945148101, 'min_child_samples': 50, 'reg_alpha': 3.812429302615472e-08, 'reg_lambda': 4.708104157466472}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[912]	valid_0's rmse: 32.6827	valid_0's l2: 1068.16
Early stopping, best iteration is:
[671]	valid_0's rmse: 24.1622	valid_0's l2: 583.812
Early stopping, best iteration is:
[372]	valid_0's rmse: 154.458	valid_0's l2: 23857.3
Early stopping, best iteration is:
[26]	valid_0's rmse: 34.2848	valid_0's l2: 1175.45

[I 2025-11-18 04:05:28,721] Trial 229 pruned.

Early stopping, best iteration is:
[482]	valid_0's rmse: 33.0929	valid_0's l2: 1095.14

[I 2025-11-18 04:05:29,030] Trial 210 finished with value: -0.5549384509375483 and parameters: {'num_leaves': 193, 'max_depth': -1, 'learning_rate': 0.09933395999684079, 'subsample': 0.6764227865934787, 'colsample_bytree': 0.7072400245212614, 'min_child_samples': 51, 'reg_alpha': 2.3240832578792181e-07, 'reg_lambda': 3.1798800884315614}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[94]	valid_0's rmse: 33.1317	valid_0's l2: 1097.71

[I 2025-11-18 04:05:29,457] Trial 218 finished with value: -0.5315465539890727 and parameters: {'num_leaves': 194, 'max_depth': 2, 'learning_rate': 0.10495266681452048, 'subsample': 0.674255773894169, 'colsample_bytree': 0.7063815900772071, 'min_child_samples': 51, 'reg_alpha': 1.1044170024796554e-05, 'reg_lambda': 9.751483114079795}. Best is trial 176 with value: -0.5248754661043161.
[I 2025-11-18 04:05:29,572] Trial 225 finished with value: -0.534757139031977 and parameters: {'num_leaves': 175, 'max_depth': 2, 'learning_rate': 0.07650341004318406, 'subsample': 0.6841245912494829, 'colsample_bytree': 0.7157531174793723, 'min_child_samples': 46, 'reg_alpha': 7.766504726546472e-08, 'reg_lambda': 5.48975622173059}. Best is trial 176 with value: -0.5248754661043161.
[I 2025-11-18 04:05:30,484] Trial 220 finished with value: -0.5334032264987029 and parameters: {'num_leaves': 175, 'max_depth': 2, 'learning_rate': 0.10330163129008722, 'subsample': 0.6741620051330358, 'colsample_bytree': 0.7436066929763981, 'min_child_samples': 51, 'reg_alpha': 1.1491868894049847e-05, 'reg_lambda': 9.995825309246824}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[249]	valid_0's rmse: 154.678	valid_0's l2: 23925.4
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:05:31,478] Trial 230 pruned.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[656]	valid_0's rmse: 24.1653	valid_0's l2: 583.96
Early stopping, best iteration is:
[54]	valid_0's rmse: 33.8445	valid_0's l2: 1145.45

[I 2025-11-18 04:05:35,598] Trial 219 finished with value: -0.5494134441050028 and parameters: {'num_leaves': 191, 'max_depth': 11, 'learning_rate': 0.10354460871002544, 'subsample': 0.676252401056052, 'colsample_bytree': 0.7036619346627491, 'min_child_samples': 44, 'reg_alpha': 6.020290167671973e-08, 'reg_lambda': 9.40519397394028}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[450]	valid_0's rmse: 32.915	valid_0's l2: 1083.4

[I 2025-11-18 04:05:36,648] Trial 226 finished with value: -0.5314011121789476 and parameters: {'num_leaves': 175, 'max_depth': 2, 'learning_rate': 0.12300354639568722, 'subsample': 0.6827547576159199, 'colsample_bytree': 0.8844955423055116, 'min_child_samples': 51, 'reg_alpha': 1.9499904853144232e-08, 'reg_lambda': 9.750428035183402}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[411]	valid_0's rmse: 154.022	valid_0's l2: 23722.7
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[647]	valid_0's rmse: 24.1483	valid_0's l2: 583.141
Did not meet early stopping. Best iteration is:
[991]	valid_0's rmse: 23.9717	valid_0's l2: 574.642
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[613]	valid_0's rmse: 155.646	valid_0's l2: 24225.7
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[546]	valid_0's rmse: 32.9616	valid_0's l2: 1086.47
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:05:41,187] Trial 228 finished with value: -0.5323135922402379 and parameters: {'num_leaves': 176, 'max_depth': 2, 'learning_rate': 0.12368201196319738, 'subsample': 0.6820092543733924, 'colsample_bytree': 0.7189774348678666, 'min_child_samples': 51, 'reg_alpha': 1.322477318303903e-05, 'reg_lambda': 5.163957601700311}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[530]	valid_0's rmse: 32.6377	valid_0's l2: 1065.22
Early stopping, best iteration is:
[563]	valid_0's rmse: 24.1089	valid_0's l2: 581.239

[I 2025-11-18 04:05:44,694] Trial 227 finished with value: -0.5314209300619268 and parameters: {'num_leaves': 176, 'max_depth': 2, 'learning_rate': 0.12678505484961866, 'subsample': 0.6827160885394251, 'colsample_bytree': 0.8834099412714216, 'min_child_samples': 51, 'reg_alpha': 4.6616603317956166e-08, 'reg_lambda': 5.101693002483362}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[657]	valid_0's rmse: 24.1559	valid_0's l2: 583.507
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[681]	valid_0's rmse: 24.1614	valid_0's l2: 583.774
Early stopping, best iteration is:
[572]	valid_0's rmse: 24.1235	valid_0's l2: 581.946
Early stopping, best iteration is:
[651]	valid_0's rmse: 24.1625	valid_0's l2: 583.829
Early stopping, best iteration is:
[692]	valid_0's rmse: 24.1616	valid_0's l2: 583.785
Early stopping, best iteration is:
[127]	valid_0's rmse: 33.1595	valid_0's l2: 1099.55

[I 2025-11-18 04:05:47,575] Trial 232 finished with value: -0.5335947944448514 and parameters: {'num_leaves': 178, 'max_depth': 2, 'learning_rate': 0.11853475346538997, 'subsample': 0.6318263768451332, 'colsample_bytree': 0.8824348879972755, 'min_child_samples': 46, 'reg_alpha': 1.234788187981185e-05, 'reg_lambda': 5.998899597169989}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[93]	valid_0's rmse: 33.1583	valid_0's l2: 1099.47
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:05:49,332] Trial 231 finished with value: -0.53802903919074 and parameters: {'num_leaves': 176, 'max_depth': 2, 'learning_rate': 0.07279671202423345, 'subsample': 0.682213998836694, 'colsample_bytree': 0.7319583805024431, 'min_child_samples': 46, 'reg_alpha': 5.881875702325748e-08, 'reg_lambda': 4.9857034905540525}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[974]	valid_0's rmse: 154.188	valid_0's l2: 23774
Early stopping, best iteration is:
[839]	valid_0's rmse: 24.015	valid_0's l2: 576.72
Did not meet early stopping. Best iteration is:
[943]	valid_0's rmse: 23.9741	valid_0's l2: 574.755
Early stopping, best iteration is:
[673]	valid_0's rmse: 24.1355	valid_0's l2: 582.524
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[688]	valid_0's rmse: 24.1288	valid_0's l2: 582.197
Did not meet early stopping. Best iteration is:
[986]	valid_0's rmse: 154.129	valid_0's l2: 23755.8
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[575]	valid_0's rmse: 24.1152	valid_0's l2: 581.544
Early stopping, best iteration is:
[721]	valid_0's rmse: 24.0144	valid_0's l2: 576.693
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[963]	valid_0's rmse: 154.065	valid_0's l2: 23735.9
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:04,610] Trial 233 finished with value: -0.5272618439379761 and parameters: {'num_leaves': 176, 'max_depth': 1, 'learning_rate': 0.11997016745153269, 'subsample': 0.6818581582097557, 'colsample_bytree': 0.8867477159525364, 'min_child_samples': 46, 'reg_alpha': 2.8472255271021953e-08, 'reg_lambda': 5.851618954702036}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[114]	valid_0's rmse: 33.3925	valid_0's l2: 1115.06
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[996]	valid_0's rmse: 153.999	valid_0's l2: 23715.8
Did not meet early stopping. Best iteration is:
[989]	valid_0's rmse: 154.034	valid_0's l2: 23726.4
Early stopping, best iteration is:
[99]	valid_0's rmse: 33.4252	valid_0's l2: 1117.25

[I 2025-11-18 04:06:09,804] Trial 235 finished with value: -0.527317219055559 and parameters: {'num_leaves': 177, 'max_depth': 1, 'learning_rate': 0.12222488507506561, 'subsample': 0.9360608396782913, 'colsample_bytree': 0.8844568182943432, 'min_child_samples': 46, 'reg_alpha': 2.3054982503371545e-08, 'reg_lambda': 6.092749026995985}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[980]	valid_0's rmse: 154.001	valid_0's l2: 23716.4
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[98]	valid_0's rmse: 33.5423	valid_0's l2: 1125.08

[I 2025-11-18 04:06:15,045] Trial 234 finished with value: -0.526384339711386 and parameters: {'num_leaves': 177, 'max_depth': 1, 'learning_rate': 0.12329013508176132, 'subsample': 0.6318875036272537, 'colsample_bytree': 0.8834785579403102, 'min_child_samples': 46, 'reg_alpha': 1.2156846676801933e-05, 'reg_lambda': 5.030102898299998}. Best is trial 176 with value: -0.5248754661043161.

Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 154.041	valid_0's l2: 23728.5
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 154.023	valid_0's l2: 23723.2
Did not meet early stopping. Best iteration is:
[927]	valid_0's rmse: 154.034	valid_0's l2: 23726.3
Did not meet early stopping. Best iteration is:
[986]	valid_0's rmse: 154.06	valid_0's l2: 23734.6
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:19,775] Trial 236 finished with value: -0.5270860320868233 and parameters: {'num_leaves': 173, 'max_depth': 1, 'learning_rate': 0.12066027524177131, 'subsample': 0.653244040128292, 'colsample_bytree': 0.8848173429925329, 'min_child_samples': 46, 'reg_alpha': 1.3826254773768268e-05, 'reg_lambda': 8.672309007689362}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[116]	valid_0's rmse: 33.4463	valid_0's l2: 1118.65
Early stopping, best iteration is:
[112]	valid_0's rmse: 33.5155	valid_0's l2: 1123.29
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:20,227] Trial 237 finished with value: -0.52714439152057 and parameters: {'num_leaves': 172, 'max_depth': 1, 'learning_rate': 0.1257248255104757, 'subsample': 0.650984013284794, 'colsample_bytree': 0.882869777167456, 'min_child_samples': 46, 'reg_alpha': 1.5346443956939613e-05, 'reg_lambda': 0.018550919572940593}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[753]	valid_0's rmse: 23.9707	valid_0's l2: 574.595
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[990]	valid_0's rmse: 153.92	valid_0's l2: 23691.3
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[110]	valid_0's rmse: 33.3414	valid_0's l2: 1111.65

[I 2025-11-18 04:06:21,398] Trial 239 finished with value: -0.5267785584325578 and parameters: {'num_leaves': 172, 'max_depth': 1, 'learning_rate': 0.12257968954501089, 'subsample': 0.6527379885803611, 'colsample_bytree': 0.882500139618963, 'min_child_samples': 46, 'reg_alpha': 1.4306540022831606e-05, 'reg_lambda': 6.272704948741934}. Best is trial 176 with value: -0.5248754661043161.

Did not meet early stopping. Best iteration is:
[925]	valid_0's rmse: 154.029	valid_0's l2: 23725
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[997]	valid_0's rmse: 153.841	valid_0's l2: 23667
Early stopping, best iteration is:
[526]	valid_0's rmse: 23.9958	valid_0's l2: 575.801
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:22,742] Trial 241 finished with value: -0.52688059472206 and parameters: {'num_leaves': 169, 'max_depth': 1, 'learning_rate': 0.12280003317187059, 'subsample': 0.6556563621559629, 'colsample_bytree': 0.8844966584346109, 'min_child_samples': 46, 'reg_alpha': 1.544292037063652e-05, 'reg_lambda': 6.27801154244535}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[19]	valid_0's rmse: 33.3636	valid_0's l2: 1113.13
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:24,510] Trial 240 finished with value: -0.527499353323692 and parameters: {'num_leaves': 170, 'max_depth': 1, 'learning_rate': 0.12181347962402056, 'subsample': 0.6520505023881528, 'colsample_bytree': 0.8843151731029629, 'min_child_samples': 46, 'reg_alpha': 5.715311031936993e-05, 'reg_lambda': 8.47592280640891}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[21]	valid_0's rmse: 33.5213	valid_0's l2: 1123.67
Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 154.127	valid_0's l2: 23755.2
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[970]	valid_0's rmse: 154.095	valid_0's l2: 23745.2
Early stopping, best iteration is:
[112]	valid_0's rmse: 33.4079	valid_0's l2: 1116.09
Early stopping, best iteration is:
[101]	valid_0's rmse: 33.3351	valid_0's l2: 1111.23

[I 2025-11-18 04:06:28,610] Trial 238 finished with value: -0.5268391808928867 and parameters: {'num_leaves': 172, 'max_depth': 1, 'learning_rate': 0.11789814009200805, 'subsample': 0.6540241104972613, 'colsample_bytree': 0.8847014018919847, 'min_child_samples': 47, 'reg_alpha': 6.915068182661275e-05, 'reg_lambda': 6.190258411313527}. Best is trial 176 with value: -0.5248754661043161.
[I 2025-11-18 04:06:28,667] Trial 242 finished with value: -0.5268258858504944 and parameters: {'num_leaves': 37, 'max_depth': 1, 'learning_rate': 0.1232747850070098, 'subsample': 0.6560861390887676, 'colsample_bytree': 0.8815031575795308, 'min_child_samples': 47, 'reg_alpha': 5.593780004437058e-05, 'reg_lambda': 0.019763930104503665}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[550]	valid_0's rmse: 23.983	valid_0's l2: 575.186
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:30,265] Trial 244 finished with value: -0.5264057235999976 and parameters: {'num_leaves': 204, 'max_depth': 1, 'learning_rate': 0.12505522242884157, 'subsample': 0.652547279661507, 'colsample_bytree': 0.8755056686566368, 'min_child_samples': 46, 'reg_alpha': 5.994053224088052e-05, 'reg_lambda': 0.012009347907460777}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[18]	valid_0's rmse: 33.558	valid_0's l2: 1126.14
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[80]	valid_0's rmse: 33.6978	valid_0's l2: 1135.54

[I 2025-11-18 04:06:31,760] Trial 245 finished with value: -0.5277272012209099 and parameters: {'num_leaves': 204, 'max_depth': 1, 'learning_rate': 0.14427171242989445, 'subsample': 0.6500785186815783, 'colsample_bytree': 0.8741430346103083, 'min_child_samples': 46, 'reg_alpha': 5.68607445870526e-05, 'reg_lambda': 0.013395200335726665}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[530]	valid_0's rmse: 24.0312	valid_0's l2: 577.5

[I 2025-11-18 04:06:32,506] Trial 243 finished with value: -0.5262153900482801 and parameters: {'num_leaves': 168, 'max_depth': 1, 'learning_rate': 0.11951245072887345, 'subsample': 0.6331235305031421, 'colsample_bytree': 0.8858057113558933, 'min_child_samples': 46, 'reg_alpha': 6.776559537741291e-05, 'reg_lambda': 0.018369412065324643}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[111]	valid_0's rmse: 33.482	valid_0's l2: 1121.04
Early stopping, best iteration is:
[531]	valid_0's rmse: 24.1023	valid_0's l2: 580.923
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[992]	valid_0's rmse: 153.905	valid_0's l2: 23686.7
Early stopping, best iteration is:
[109]	valid_0's rmse: 33.4183	valid_0's l2: 1116.78

[I 2025-11-18 04:06:33,847] Trial 246 finished with value: -0.527045272200922 and parameters: {'num_leaves': 168, 'max_depth': 1, 'learning_rate': 0.11807276231150993, 'subsample': 0.653379833124882, 'colsample_bytree': 0.8716748157167685, 'min_child_samples': 46, 'reg_alpha': 4.962957679717673e-06, 'reg_lambda': 6.008877359241908}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[559]	valid_0's rmse: 24.0709	valid_0's l2: 579.408
Training until validation scores don't improve for 100 rounds
Early stopping, best iteration is:
[80]	valid_0's rmse: 33.6853	valid_0's l2: 1134.7

[I 2025-11-18 04:06:34,836] Trial 248 finished with value: -0.5279355761653126 and parameters: {'num_leaves': 170, 'max_depth': 1, 'learning_rate': 0.1446831330587184, 'subsample': 0.653740512303563, 'colsample_bytree': 0.8723980493678661, 'min_child_samples': 46, 'reg_alpha': 5.398069116023933e-06, 'reg_lambda': 8.174126401249328}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[45]	valid_0's rmse: 26.1249	valid_0's l2: 682.511
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:38,164] Trial 247 finished with value: -0.5261213430254607 and parameters: {'num_leaves': 170, 'max_depth': 1, 'learning_rate': 0.1405776711722025, 'subsample': 0.6545102377573728, 'colsample_bytree': 0.8694515722780107, 'min_child_samples': 46, 'reg_alpha': 5.4138557280414166e-05, 'reg_lambda': 7.97784587523978}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[77]	valid_0's rmse: 33.4645	valid_0's l2: 1119.87
Did not meet early stopping. Best iteration is:
[983]	valid_0's rmse: 153.925	valid_0's l2: 23693
Did not meet early stopping. Best iteration is:
[980]	valid_0's rmse: 153.934	valid_0's l2: 23695.6
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[975]	valid_0's rmse: 153.827	valid_0's l2: 23662.7
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[997]	valid_0's rmse: 153.842	valid_0's l2: 23667.4

[I 2025-11-18 04:06:44,520] Trial 250 finished with value: -0.5263147322962699 and parameters: {'num_leaves': 168, 'max_depth': 1, 'learning_rate': 0.14260976746658835, 'subsample': 0.6574270758574319, 'colsample_bytree': 0.8712679938645166, 'min_child_samples': 48, 'reg_alpha': 6.290746846607186e-05, 'reg_lambda': 0.012660192774760187}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[16]	valid_0's rmse: 33.5351	valid_0's l2: 1124.6
Early stopping, best iteration is:
[84]	valid_0's rmse: 33.5343	valid_0's l2: 1124.55

[I 2025-11-18 04:06:44,772] Trial 249 finished with value: -0.5261316412266325 and parameters: {'num_leaves': 170, 'max_depth': 1, 'learning_rate': 0.14138826478745814, 'subsample': 0.6531325445454684, 'colsample_bytree': 0.8683522239909084, 'min_child_samples': 41, 'reg_alpha': 5.561836607201241e-05, 'reg_lambda': 8.182114703685478}. Best is trial 176 with value: -0.5248754661043161.

Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:46,090] Trial 251 finished with value: -0.5266110614559915 and parameters: {'num_leaves': 168, 'max_depth': 1, 'learning_rate': 0.1443586903052311, 'subsample': 0.6158302509405357, 'colsample_bytree': 0.8714762634870463, 'min_child_samples': 48, 'reg_alpha': 6.76458060548603e-05, 'reg_lambda': 3.349433791542815}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[71]	valid_0's rmse: 33.6765	valid_0's l2: 1134.11
Training until validation scores don't improve for 100 rounds
Did not meet early stopping. Best iteration is:
[976]	valid_0's rmse: 153.696	valid_0's l2: 23622.5

[I 2025-11-18 04:06:47,202] Trial 252 finished with value: -0.5275066517822513 and parameters: {'num_leaves': 168, 'max_depth': 1, 'learning_rate': 0.14778556167945758, 'subsample': 0.6660100869496954, 'colsample_bytree': 0.87124269407539, 'min_child_samples': 48, 'reg_alpha': 0.00014089150653274278, 'reg_lambda': 3.746368419008398}. Best is trial 176 with value: -0.5248754661043161.

Did not meet early stopping. Best iteration is:
[999]	valid_0's rmse: 153.869	valid_0's l2: 23675.8
Early stopping, best iteration is:
[80]	valid_0's rmse: 33.8196	valid_0's l2: 1143.76

[I 2025-11-18 04:06:47,525] Trial 253 pruned.

Early stopping, best iteration is:
[55]	valid_0's rmse: 157.29	valid_0's l2: 24740.2
Training until validation scores don't improve for 100 rounds
Training until validation scores don't improve for 100 rounds

[I 2025-11-18 04:06:48,336] Trial 254 finished with value: -0.5272404258507002 and parameters: {'num_leaves': 186, 'max_depth': 1, 'learning_rate': 0.14555168466025947, 'subsample': 0.6650010288523625, 'colsample_bytree': 0.8731885617284568, 'min_child_samples': 41, 'reg_alpha': 5.7761061094600283e-05, 'reg_lambda': 0.012832203732687751}. Best is trial 176 with value: -0.5248754661043161.
[I 2025-11-18 04:06:48,474] Trial 255 finished with value: -0.5263505202877905 and parameters: {'num_leaves': 43, 'max_depth': 1, 'learning_rate': 0.14019452232644736, 'subsample': 0.6122955883357384, 'colsample_bytree': 0.8724620419909139, 'min_child_samples': 41, 'reg_alpha': 5.362265104763842e-05, 'reg_lambda': 3.8799414732868454}. Best is trial 176 with value: -0.5248754661043161.

Early stopping, best iteration is:
[79]	valid_0's rmse: 33.6866	valid_0's l2: 1134.79
Early stopping, best iteration is:
[84]	valid_0's rmse: 33.4409	valid_0's l2: 1118.3
[Optuna-LGBM] Best score: -0.5248754661043161
[Optuna-LGBM] Best params: {'num_leaves': 182, 'max_depth': 1, 'learning_rate': 0.1376487510667218, 'subsample': 0.6646570414741191, 'colsample_bytree': 0.8579018466891751, 'min_child_samples': 48, 'reg_alpha': 2.5033847143506212e-05, 'reg_lambda': 3.188772872548122}
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.010491 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 7320
[LightGBM] [Info] Number of data points in the train set: 42573, number of used features: 29
[LightGBM] [Info] Start training from score 99.681522
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 100 rounds
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [13]:
evaluate_model(final_model, X_test, y_test)

  property metric      score
0     bias   rmse  46.551135
1     bias  nrmse   0.534237